### ISSUE TITLE
cli installation downloads 1.8GB of eth2-spec-test

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1144]
**Describe the bug**
Installing the package @chainsafe/lodestar-cli download the eth2-spec-test adding 1.8GB of added unnecessary disk usage.

**Expected behavior**
Do not download unnecessary tests

**Steps to Reproduce**
```
yarn add @chainsafe/lodestar-cli
```

**Comment by ltfschoen** [comment]
It says in the CONTRIBUTING.md file that you can avoid it downloading unnecessary tests specs https://github.com/ChainSafe/lodestar/blob/master/CONTRIBUTING.md#getting-started by running `yarn install --ignore-optional`, so perhaps in your case you could also run `yarn add @chainsafe/lodestar-cli --ignore-optional`?

Perhaps such parts of that CONTRIBUTING.md file should also be mentioned in the docs at https://chainsafe.github.io/lodestar/installation/

**Comment by dapplion** [comment]
@ltfschoen You are right, `--ignore-optional` prevents the test specs from downloading. However, I wonder it's the best approach to require any consumer of lodestar to install always with `--ignore-optional` when there's not an intention of running the tests.

**Comment by ltfschoen** [comment]
@dapplion I'm new to this codebase and I wonder the same, as I didn't realise there was the `--ignore-optional` option to avoid downloading all the test specs when I initially started working on this repo yesterday, but that was because it was mentioned in CONTRIBUTING.md rather than also in the docs website that I was following.
