### ISSUE TITLE
enable signature verification in initial sync

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#1217]
pending answer to “In initial sync, do we need to verify ALL operations? or just block signature?"

**Comment by dapplion** [comment]
@tuyennhv Would you mind assessing the viability of this now that we have BLST?

**Comment by twoeths** [comment]
> @tuyennhv Would you mind assessing the viability of this now that we have BLST?

I have some statistics when I sync mainnet until block 28000:
+ lighthouse takes less than 10 minutes with signature verification
+ lodestar takes almost 1h without signature verification (due to the single thread nature)

so I think we have to wait for #1771  first where we send a block range to do state transition and verify multiple signatures at the same time. We'll see which signatures we want to verify at that time.

**Comment by dapplion** [comment]
With batch signature verification we can achieve 50% savings in the best case scenario so it won't help much if are still an order of magnitude away.

**Comment by dapplion** [comment]
Would be very valuable to know how much time is currently spent doing signature verification. Then we know if we have to focus on optimizing the state transition function itself or signature verification

**Comment by twoeths** [comment]
> `lodestar takes almost 1h without signature verification (due to the single thread nature)`

as I said above, for initial sync we don't do any signature verification for now so if we do, the time to sync is much bigger.

if we plan on having signature verification for initial sync, we need to work on #1771 first before we bench mark.

**Comment by dapplion** [comment]
Sorry just closed the issue, BLST is already integrated in current master

**Comment by dapplion** [comment]
@tuyennhv As I summarized in https://github.com/ChainSafe/lodestar/issues/1771
In terms of speeding up signature verification, it has 3 steps
- Change herumi for BLST, x10 speed increase :heavy_check_mark: 
- Use batch verification x2 speed increase :hourglass: 
- Multi-thread x2-x8 speed increase :question: 

So the most impactful speed increase is already delivered. That's why I think it's a good time to benchmark how good or bad are we right now.

**Comment by twoeths** [comment]
thanks for the clarification @dapplion , we haven't applied signature verification for initial sync yet so there's no difference when BLST is in.

**Comment by twoeths** [comment]
The below statistic is from Pyrmont syncs till slot 5000 in my local environment and latest master `83c2949`

| Desc | # | Duration | Max Block Transition Time |
| - | - | - | - |
| No signature verification | 1 | 30 minutes | 9418ms at slot: 2368 |
| No signature verification | 2 | 24 minutes | 4767ms at slot: 3584 |
| Block signature verification | 1 | 22 minutes | 4693ms at slot: 2624 |
| Block signature verification | 2 | 21 minutes | 4246ms at slot: 4576 |
| All operations signature verification | 1 | 42 minutes |  5609ms at slot: 1984 |
| All operations signature verification | 2 | 48 minutes |  4327ms at slot: 3264 |

not sure why verifying block signature takes less time although I run twice but at least it's comparable to no signature verification.

**Comment by dapplion** [comment]
@tuyennhv Thanks for benchmarking this! @wemeetagain Do you think it would be valuable to profile a couple of blocks and check what's the actual time spent in BLS signature verification on a small sample?

**Comment by wemeetagain** [comment]
Yes, I think that would be good to more deeply understand these results.

I personally don't understand how "block signature verification" could possibly be faster than "no block signature verification".

**Comment by dapplion** [comment]
Fixed with https://github.com/ChainSafe/lodestar/pull/2147
