### ISSUE TITLE
Throw specific errors in lodestar/api

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1293]
Throw identifiable errors that can be converted to HTTP error codes if necessary in api/rest or another implementation

---

Not in this PR but we should make this error more sensible so we can trow 400 in case of this error.

_Originally posted by @mpetrunic in https://github.com/ChainSafe/lodestar/pull/1290_

**Comment by dapplion** [comment]
unstale

**Comment by dapplion** [comment]
@mpetrunic Could you outline a specific example implementation for this? Then I can take the issue

**Comment by mpetrunic** [comment]
As you can see we have global rest api error handler (anything that isn't caught in api controller ends up being handled here):
https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/api/rest/routes/error.ts

Since we already have ApiError handling, my idea was that inside api we throw children of ApiError.
Some example would be:
Instead of this handling here: https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/api/rest/controllers/beacon/state/getStateFinalityCheckpoints.ts#L24

We would just throw `InvalidStateIdError extends ApiError` and let global handler format error response

**Comment by dapplion** [comment]
Would you mind taking this issue since you are more familiar with the API internals?

**Comment by 3xtr4t3rr3str14l** [comment]
@mpetrunic is this something you have been working on and/or have already finished?

**Comment by mpetrunic** [comment]
Not actively, but my api PRs includes those changes, there is probably some places where it's still present in beacon api.
