### ISSUE TITLE
Delete peer from peer store if unsupported protocol

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1430]
**What is your question?**

When we find peer, it get's stored in peer store and persisted on disk. When we restart we loose a lot of time probing those same peers that doesn't support status rpc protocol (maybe different chain or something).

Should we delete peer from peer store on unsupported protocol? Would be even better if we could keep blacklist in peerstore so we don't attempt to connect again

**Comment by wemeetagain** [comment]
I think we should set up peer metadata (score, protocol support, etc) in the metadata store (so its persisted, rather than delete peers. There's also the [`ProtoBook`](https://github.com/libp2p/js-libp2p/blob/master/src/peer-store/proto-book.js) that might be persisting supported protocols already, we might look into that.

If we delete bad peers, we risk discv5 continuously re-sending that peer to libp2p.

**Comment by mpetrunic** [comment]
I'll take this and improve our peer usage overall (just active peers with supported protocols)
