### ISSUE TITLE
Consider not requiring from `modules/lib/path/to/file`

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1462]
**Is your feature request related to a problem? Please describe.**
I believe requiring specific module paths is an anti-pattern since we are coupling the file structure of a module with its consumer. The internal structure of a module should not matter, everything that has to be used should be exported in the root.

**Describe the solution you'd like**
Export everything that's used in the module main file.

**Comment by dapplion** [comment]
Some modules (Lodestar utils ?) may want to namespace components to allow tree-shaking (i.e. https://github.com/ethereum/js-ethereum-cryptography). If that's the case do it good.

**Comment by dapplion** [comment]
unstale

**Comment by 3xtr4t3rr3str14l** [comment]
Looks like we probably we won't be able to do this in full until we figure out what to do about lodestar-beacon-state-transition (do we put the fast state transition in its own package?  remove the old version from `util/` and just use that, etc, as tracked in #1624).  Right now, we are doing things such as `import {computeSubnetForAttestation} from "@chainsafe/lodestar-beacon-state-transition/lib/fast/util/attestation";` because if we don't refer explicitly to the `fast` folder, then the IDE thinks we are talking about the version in `util`.

**Comment by dapplion** [comment]
@3xtr4t3rr3str14l If you want you can finish this open PR https://github.com/ChainSafe/lodestar/pull/1721
It just needs work to fix the tests and should be good to go
