### ISSUE TITLE
Discussion: unit test stubbing

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1523]
#### Background

When doing the eth1 data for block processing refactor I had to update a lot of stubbed unit tests just because I changed the implementation slightly. A great example of a stubbed unit test is this one:

https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/test/unit/chain/factory/block/blockAssembly.test.ts

What is this test trying to verify or prove? Apparently, it only asserts a bunch of functions are called in the implementation. It's almost an identical implementation of the original implementation but with more code.

#### Proposal

In my personal opinion, the test linked above is more of a liability than an asset to this codebase. I would like to know other contributors' thoughts about testing to try to improve it going forward.

1. Whenever possible isolate all logic into pure functions that can be tested just by feeding them values and asserting the result.
2. "Delegator functions" like `blockAssembly` should not be tested at all. Prevented that, (1) their implementation is so simple that a test is not necessary and (2) exist an end-to-end test (maybe many abstractions above) that uses the function and would fail if delegation is not done properly.

**Comment by mpetrunic** [comment]
blockAssembly method is not simple and it currently just checks if in happy path all block fields are set. Value correctness are not tested as it depends on other methods which we expect to work correctly. What this test do lack is most important part of unit testing, error paths like state context is missing, head block is missing etc.

**Comment by dapplion** [comment]
Following your point I would suggest do abstract blockAssembly to fit this layout
```ts
async function doSomething(db: Db) {
  const values = await db.something.values();
  return doSomethingLogic(values);
}
```
Where `doSomething` exclusively collects values and calls pure functions encapsulating the logic. Then you test error paths and everything else in `doSomethingLogic` with mock values only, instead of stubbed classes.

**EDIT**
This issue is inspired by the feeling that the current usage of stubs in the lodestar codebase is not optimal. In many tests stubs are defined in the parent scope with `any` type which is evil
https://github.com/ChainSafe/lodestar/blob/3492e8e7973baeb4a75e4575d7017cfa2310cd67/packages/lodestar-beacon-state-transition/test/unit/stateTransition/block/operations/voluntaryExit.test.ts#L16
As a new-comer, I have a hard time reading the tests and understanding what they are trying to prove. Most of the code ends up being boilerplate that doesn't add meaningful information. The goal of this issue is to find better ways to test the codebase in more elegant and correct ways.

**Comment by mpetrunic** [comment]
> This issue is inspired by the feeling that the current usage of stubs in the lodestar codebase is not optimal. In many tests stubs are defined in the parent scope with any type which is evil

Oh yeah, thats real problem that occurred because lack of lint rules/lack of knowledge what types should be. It's a lot easier in tests where type is `StubbedInstance<IBeaconChain>`. 

> Where doSomething exclusively collects values and calls pure functions encapsulating the logic. Then you test error paths and everything else in doSomethingLogic with mock values only, instead of stubbed classes.

Maybe it's just me, but I'm finding stubbed methods/classes a lot more expressive than having methods
where all params can be null and you have to throw errors in that case. I think it just comes down whether we wanna write boilerplate tests or boilerplate code (abstracting every small logic part into separate function).

It's not really black and white, I like small logical functions but I feel that in blockAssembly is a bit pointless as it makes code context harder to follow.

**Comment by wemeetagain** [comment]
:+1: Definitely agree with OP. I also feel like we abuse stubs in some cases to test internal implementation details. We shouldn't be doing things checking `stubbedMethod.calledOnce` to determine if a code path is taken.

I think there are two big cases cases where we're over-using stubs:
1. We're trying to trigger some sort of behavior based on chain state - In this case, we don't have good infrastructure to generate meaningful chain states, and it ends up being very "convenient" to just stub things. Eg: since committees/proposers depend on randao we might stub to force a certain validator index to be proposer.
A better path would be to build up the necessary infra to generate states with certain properties and also to decompose functions into testable pieces that no longer rely on a very specifically-crafted chain state.
2. We're stubbing submodules to test "delegator" functions and module methods. I think at this level, either e2e tests or unit tests of smaller functions are much more valuable.
Stubs can be used to test and can provide valuable tests, but imo in most cases, refactoring as in your `doSomething` example is a good idea. The inner `doSomethingLogic` can have cleaned up types, and need not include trivially incorrect cases (eg: null values), which can be checked in `doSomething`. The benefit of this approach is that higher-level modules which mostly call inner functions and hold state can be more easily refactored. Tests will also have less boiler plate and can interact with only "real" values.

> It's not really black and white

Agree with this too. IMO its not worth tearing down what we have entirely to enforce some sort of anti-stubbing policy. I think a good course of action is simply to be mindful about how we design modules and test _going forward_ and make sure the tests that we _do_ maintain are actually providing value and have a strong purpose.

**Comment by mpetrunic** [comment]
> A better path would be to build up the necessary infra to generate states with certain properties and also to decompose functions into testable pieces that no longer rely on a very specifically-crafted chain state.

I don't like this at all, that something e2e tests should have because:
1. it will make unit tests slower, while we should aim them to be faster
2. slight change to state structure could invalidate our infra to generate specifically-crafted chain state

>  The inner doSomethingLogic can have cleaned up types, and need not include trivially incorrect cases (eg: null values)

It cannot, it has to support null argument values or you would have to forcefully cast values when using `doSomethingLogic`.

Stubs are you friends, we have examples where stubs provide wonderful tests but it all depends on how "testable" code you write. By providing values and expecting some result you can easily miss paths like method called twice/or none that resulted in same returned value which could've been easily detected with `stubbedMethod.calledOnce` . We can just as easily have nightmare tests with obfuscating logic into "logic" functions.

**Comment by dapplion** [comment]
After +1.5y I would conclude:

- Completely forbid import stubbing. It's incredibly painful to maintain, and has caused us a lot of issues when migrating to higher TS versions, ESM, etc.
- Recommend to avoid stubbing when other approaches are feasible. For example:
  - generate valid test data
  - design your functions are pure
  - design your functions with plug-able dependencies to have built-in stubbing

Stubbing is a valuable tool, but it's usually the "lazy option" increasing the cost to maintainers down the line. It also offers very poor real coverage, providing a false sense of security when adding those tests.

if there's no opposition, @philknows can you add this notes to contributing doc?

**Comment by nazarhussain** [comment]
I am late to discussion, but here is my thoughts. 

Based on my experience I would disagree to your conclusion for the sinon. If used properly and with right patterns, it's always best to use stubs and spies in the unit tests. There is no harm in using sinon based stubs to replace dependencies, even if we don't need to assert any of it's behavior. It's better approach for test mocks.

The rule of thumb is: 

> The unit tests focus on a unit and all dependencies can be replaced with mocks. So using sinon or related libraries in unit tests are highly encouraged. 

The issues that one may face could be because of these patterns. 

1. Not setting up and clearing the stubbed environments e.g. sinon sandbox. 
2. Not clearing up the stubbed counters which are consumed in assertions. 
3. Mis-matched mocks with actual implementation. 
4. Having multiple mocks for same behavior instead of re-using one. 

Related to the points mentioned above. 

**generate valid test data**
That's should be done always when the unit under test is dependent on that data. This point is true for all testing scenarios, not just for unit tests. 

**design your functions are pure**
Having pure functions does not mean, all the dependencies which are passed through arguments must be captured from the return values. e.g. logger, metrics. If for a unit tests we want to assert any such behavior which is not captured through output requires to pass spies and stubs. 

**design your functions with plug-able dependencies to have built-in stubbing**
There is no concept **built-in** stubbing. If you are referring to auto-mocking the dependencies, that goes against earlier argument of avoiding stubbing. As of my experience, having explicit mocks are more readable than auto mocks.
