### ISSUE TITLE
Implement upnp for port forwarding

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1797]
https://www.npmjs.com/package/nat-api

Suggested by @mpetrunic in lodestar's Discord

**Comment by dapplion** [comment]
With libp2p punching NAT holes so efficiently is this necessary for our needs?

**Comment by mpetrunic** [comment]
how do you mean? Afaik, we are only having peers that we find and connect to us while nobody can discover and connect to us

**Comment by dapplion** [comment]
> how do you mean? Afaik, we are only having peers that we find and connect to us while nobody can discover and connect to us

I've run lodestar behind a NAT and kept a stable peer count. libp2p uses all sorts of tricks to allow connections even if you are not directly reachable https://docs.libp2p.io/concepts/nat/

**Comment by mpetrunic** [comment]
> > how do you mean? Afaik, we are only having peers that we find and connect to us while nobody can discover and connect to us
> 
> I've run lodestar behind a NAT and kept a stable peer count. libp2p uses all sorts of tricks to allow connections even if you are not directly reachable https://docs.libp2p.io/concepts/nat/

If you find and connect to peer, nat is irrelevant but other nodes cannot find and connect you so you can only depend on nodes you can find.

 It's somewhat important to have incoming connections because if there is great surge of new nodes (which will probably find same nodes as we), we would get kicked (nodes are instructed to allow new nodes to connect) and end up with not enough nodes/peers. 

As said on your link, libp2p has methods to traverse nat but I'm not sure if js-libp2p implement those (maybe some) and I'm definitely sure that we don't update external ip and port from libp2p and put it in our enr.

**Comment by dapplion** [comment]
> As said on your link, libp2p has methods to traverse nat but I'm not sure if js-libp2p implement those (maybe some) and I'm definitely sure that we don't update external ip and port from libp2p and put it in our enr.

Right I've noticed that too, that's important

**Comment by dapplion** [comment]
Actually it's already implemented by libp2p

**Comment by dapplion** [comment]
Tracked in https://github.com/ChainSafe/lodestar/issues/3215
