### ISSUE TITLE
lodestar-validator missing @chainsafe/lodestar-db dependency

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#1818]
**Describe the bug**

Missing @chainsafe/lodestar-db dependency dependency in package.json

**Expected behavior**

For dependency to list and auto install.
We had eslint rule that was checking those things. Seems like it stopped working.

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version: 
 - Branch: 
 - Commit hash:

**Comment by 3xtr4t3rr3str14l** [comment]
so, i tried modifying the existing entry we have for `import/no-extraneous-dependencies` eslintrc.js in the monorepo root with the following:
```
"import/no-extraneous-dependencies": ["error", {
      "devDependencies": true,
      "optionalDependencies": false,
      "peerDependencies": false,
      "packageDir": ['./', '../../'],
    }],
```

as well as commenting out this line (in order to turn the rule back on):
https://github.com/ChainSafe/lodestar/blob/5162c9136854c8c0b3816bb7622468ee0f3cc61b/.eslintrc.js#L93

The above won't throw a linting error when `@chainsafe/lodestar-db` is missing from the package.json.  However, when I tried to remove the `@chainsafe/bls` package from the lodestar-validator package.json, it did trigger a linting error for the above rule.  BUT, when I tried to remove `@chainsafe/lodestar-beacon-state-transition` from package.json, it did not trigger a linting error.  

So, it looks to me like we maybe we would have to modify the eslint rules somehow to allow monorepo sibling packages to be considered extraneous packages during linting, which I'm not sure how to do at the moment.  I tried looking for a little bit, but couldn't find anything off hand.  Open to suggestions if anyone knows how to do this.

>  We had eslint rule that was checking those things. Seems like it stopped working.

@mpetrunic , when you say this, do you mean that the eslint rule we used to have also checked for missing dependencies that are also monorepo sibling packages?

**Comment by mpetrunic** [comment]
That plugin worked for that before.

`devDependencies: true` should only be set in test files.

I bet it's error with packageDir, potential solution:
https://github.com/benmosher/eslint-plugin-import/issues/1174#issuecomment-509965883

**Comment by dapplion** [comment]
Fixed 

https://github.com/ChainSafe/lodestar/blob/4a014f0cc3a5292f033b6ebece7059b8e994cb55/packages/lodestar-validator/package.json#L50
