### ISSUE TITLE
Proposal to store less State Context inside StateContextCache

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2051]
**Is your feature request related to a problem? Please describe.**
As noted in #2005, we store too many State Contexts inside StateContextCache during initial sync unnecessarily

**Describe the solution you'd like**
+ Create one more index inside StateContextCache to know the epoch of each State Contexts
+ do `pruneFinalized` if an epoch is finalized
+ keep doing the existing `prune` per check point and make sure `MAX_STATES` there

**Comment by dapplion** [comment]
I think we can develop a much smarter StateContextCache that self-prunes given some conditions:
- We can track how many times a state cache has been accessed, the last time it has been accessed and delete the ones that are therefore less useful.
- It is possible for this instance to be self-aware of a memory constraint situation. If the memory is tight it could then drop more cached states, between a MIN and MAX number. We could also add a MIN_TIME_TO_KEEP variable in epochs
  - In NodeJS, `process.memoryUsage()`
  - In the browser: `window.performance.memory` https://trackjs.com/blog/monitoring-javascript-memory/
- A super cool solution with a feature that just landed NodeJS v14 is WeakRef. It would allow the cache'd states to be usable until they get garbage collected, not preventing to do so if the engine deems necessary. Ref: https://v8.dev/features/weak-references

All three points are complimentary and could be implemented together and optionally depending on the available features

**Comment by wemeetagain** [comment]
> Create one more index inside StateContextCache to know the epoch of each State Contexts
> do pruneFinalized if an epoch is finalized
> keep doing the existing prune per check point and make sure MAX_STATES there

This seems like an easy solution for the initial sync case. Perhaps we might even call `pruneFinalized` something like `pruneBeforeEpoch` and then `on('checkpoint', (c) => cache.pruneBeforeEpoch(c.epoch))` to prune all cached states before the most-recently processed checkpoint.
The question is then where to manage/attach this handler. I was hoping that @dapplion 's sync work would be landed at this point, might give a good place to attach this handler. Otherwise we could just add another task. (Though, I was hoping to avoid adding new tasks and rethink how the 'tasks' work. Replace the general-purpose 'task' with purposeful manager objects. Eg: Archive tasks -> `ChainArchiver`)

---

> We can track how many times a state cache has been accessed, the last time it has been accessed and delete the ones that are therefore less useful.

We likely need more investigation and thinking / asking other clients before picking a strategy for pruning. For instance, it may be that states that have been most accessed are less likely to be accessed in the future. Or that states get superseded by newer states. Or that we don't need to keep states on epoch boundaries.
Initial syncing has vastly different requirements from regular syncing. Regular syncing in a healthy network may have vastly different requirements from regular syncing in a thrashing network. etc etc.

> It is possible for this instance to be self-aware of a memory constraint situation.

I tend to think the control should be at a higher level in the stack. Partially bc the pruning strategy may depend on syncing state or other higher-level metrics. Partially bc the memory in this cache is shared between the other state cache (and more robust control of the memory requires coordinating pruning of both caches).
