### ISSUE TITLE
libp2p.dialProtocol promises are retained in memory

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2181]
**Describe the bug**

This is from a heap snapshot I use to sync Pyrmont

<img width="1177" alt="retained_eth2_Stream" src="https://user-images.githubusercontent.com/10568965/111412540-27632400-870f-11eb-83db-ab2d633a15f7.png">

**Expected behavior**

+ The stream and Promise are not retained in memory
+ `finalizeRoot` should not carry the Tree object

**Steps to Reproduce**

+ Sync Pyrmont

**Comment by twoeths** [comment]
this is another view where the retained tree stay in `finalizedRoot` of Status message
<img width="1159" alt="retained_Tree_finalizedRoot" src="https://user-images.githubusercontent.com/10568965/111433211-97ce6d00-8730-11eb-963b-6bf59ba8b906.png">

All retained trees in Status message takes ~200MB

**Comment by twoeths** [comment]
so the `libp2p.dialProtocol` promises were retained in memory, and it keeps the stream with it while the `stream.sink` keeps the `requestEncode` generator along with `finalizeRoot` (and a tree)
<img width="914" alt="retained_dialProtocol_promise" src="https://user-images.githubusercontent.com/10568965/111605028-88225780-8808-11eb-9521-2c386818a42c.png">

and the retained `libp2p.dialProtocol` promises happen with other protocols as well (`beacon_blocks_by_range` and `ipfs` etc.), not just `status`.

**Comment by dapplion** [comment]
In regards to the finalizedRoot:

When accessing a property of the state, a new SubTree is created which holds a reference to the parent tree (the entire state). For example here:

https://github.com/ChainSafe/lodestar/blob/867db03a5841f13d50355f0aeaa55062ff0e10e4/packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts#L293

ssz getter code: https://github.com/ChainSafe/ssz/blob/d6efe104a3bdc2d2beebc47af8234a3e40d414f4/src/backings/tree/container.ts#L142
```ts
getProperty<V extends keyof T>(target: Tree, property: V): PropOfTreeBacked<T, V> {
   ...
      return fieldType.tree.asTreeBacked(this.getSubtreeAtChunk(target, chunkIndex)) as PropOfTreeBacked<T, V>;
  }
```

persistent-merkle-tree code:
https://github.com/ChainSafe/persistent-merkle-tree/blob/44ec217a1531137ef9d9ebdd2fdf653559e3d4d6/src/tree.ts#L83
```ts
getSubtree(index: Gindex): Tree {
    return new Tree(this.getNode(index), (v: Tree): void => this.setNode(index, v.rootNode));
  }
```

So if someone grabs `finalizedCheckpoint` from the ForkChoice and keeps that for long the entire state won't ever be garbage collected.
- Is this expected? This behavior can cause un-expected memory leaks very hard to trace since random variables could be holding to big state without being immediately obvious.
- Could `finalizedCheckpoint` be cloned to break that reference?
- Could the automatic binding of subTrees be configurable somehow? How often we need a binded subtree vs how often don't?

**Comment by dapplion** [comment]
Proposed solution https://github.com/ChainSafe/ssz/issues/83#issuecomment-803662035

**Comment by dapplion** [comment]
This seems to be fixed completely with https://github.com/ChainSafe/persistent-merkle-tree/pull/26
