### ISSUE TITLE
getGitData script may stop Docker build if broken git repo

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2205]
**Describe the bug**

User in Lodestar channel reported broken Docker build due to a corrupted git repo. Re-downloading fixed this issue. This script seems to be the problem. 

https://github.com/ChainSafe/lodestar/blob/ea28e72fb27ba03ffa5fe7749e8dfd66c423856b/scripts/getGitData.js#L8

https://discord.com/channels/593655374469660673/593655641445367808/822147795581796433

![unknown](https://user-images.githubusercontent.com/35266934/111701095-99845780-883a-11eb-9bad-dd8193bc5159.png)

It is very useful for metrics to access git data, but maybe it should not stop the build, and be wrapped in a try-catch. Possible fixes:
- Wrap in a try / catch, log error and continue build
- Wrap in a try / catch, an stop build
- Leave as is

Possibly the cause of https://github.com/ChainSafe/libp2p-ts/issues/20

**Comment by g11tech** [comment]
I have a bit more info of how this was happening, It wasn't really git corruption (which i figured out later), but what i had done was added this as a submodule inside a repo which i use to track my active projects. <<git submodule add...>>
In that scenario when the code is build, it breaks exactly because of the code segment pinpointed by you :).

**Comment by dapplion** [comment]
Fixed
