### ISSUE TITLE
Improve PeerDiscovery.discoverPeers at PeerManager hearbeat

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2237]
**Describe the bug**

At https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/network/peers/discover.ts#L53, I added:
```
    console.log("@@@ discoverPeers, maxPeersToDiscover", maxPeersToDiscover, "notConnectedPeers", notConnectedPeers.length, "time", Date.now() - start);

```

in my environment, it printed out

```
@@@ discoverPeers, maxPeersToDiscover 24 notConnectedPeers 8092 time 1012
```

Normally it takes ~400ms but sometimes it jumps to more than 1s.

**Comment by dapplion** [comment]
I've profiled current master and this line seems to take the most time
https://github.com/ChainSafe/lodestar/blob/0f5e44c8a114e4c8a490d82aaa7fd5c030f02a0b/packages/lodestar/src/network/peers/discover.ts#L47

![Screenshot from 2021-03-24 09-08-26](https://user-images.githubusercontent.com/35266934/112276190-c1cbe600-8c80-11eb-9578-5b9275a88b4e.png)

![Screenshot from 2021-03-24 09-08-48](https://user-images.githubusercontent.com/35266934/112276196-c4c6d680-8c80-11eb-8b55-f4291ee38d7c.png)

The issue is this line that will do crypto opts on all peers in the store (potentially 1000-2000 every heartbeat)
```js
    storedPeers.forEach((idStr) => {
      peersData.set(idStr, this.get(PeerId.createFromCID(idStr)))
    })
```
https://github.com/libp2p/js-libp2p/blob/b89445274d9a30beaa447a8ce05c2367109cc8a4/src/peer-store/index.js#L104
