### ISSUE TITLE
Benchmark + optimize aggregate and proof validation

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2306]
Metrics from Prater in one of our Contabo VPS S size nodes, show that when the node is synced 80% of CPU time is spent validating aggregate and proof gossip messages. To keep up we also drop 35% of all received messages.

![Screenshot from 2021-03-31 09-21-52](https://user-images.githubusercontent.com/35266934/113114663-dcb3d280-920b-11eb-8656-8b4b77b66be0.png)

The average job duration is 20-30ms. In Prater stable conditions all attestation target states should be in the cache and cost 0 to get. Then the only big cost is signature validation, which has 3 (selection proof + aggregator sig + att sig aggregate). A BLS sig costs between 1-2 ms, and since the 3 sigs are verified in batch it should have a discount of ~50%. So the total job time should be between 1.5-3ms.

We should investigate the performance of that validation since there is significant room for improvement.

**Comment by tuyennhv** [comment]
found duplicate SignedAggregateAndProof
```
Apr-06 02:20:50.858 [NETWORK]          ^[[32minfo^[[39m: @@@ validateAggregatedAttestation slot=96703, aggregator=7760, signature=0xa7950b19d1805589aa59427701d9c9770842addc071f4b262af21468bc4371f9b48487d90b089b9f5d6f61ab4ddc30d419489aab6104dd2800aae5ba54bdd07cc065820a370ebb2372c973dc9c8b6a8fd51bc24374a926adfb84e7768d2de6f7, hash=0x03e7c0720870e581af028a305ef87ad53a2e3eb8dd885905630928e9c0205473
Apr-06 02:20:51.454 [NETWORK]          ^[[32minfo^[[39m: @@@ validateAggregatedAttestation gossip - AggregateAndProof - accept slot=96703, aggregator=7760, signature=0xa7950b19d1805589aa59427701d9c9770842addc071f4b262af21468bc4371f9b48487d90b089b9f5d6f61ab4ddc30d419489aab6104dd2800aae5ba54bdd07cc065820a370ebb2372c973dc9c8b6a8fd51bc24374a926adfb84e7768d2de6f7, hash=0x03e7c0720870e581af028a305ef87ad53a2e3eb8dd885905630928e9c0205473
```

**Comment by twoeths** [comment]
+ there are almost 600 different aggregate and proof items per slot, each `validateAggregateAttestation` call takes 6ms in average (some exceptional ones may take up to 60ms due to gc), most of the time this function does is to do batch signature verification. For this, we should consider increasing our job queue size.

+ there are some duplicate attestations (with different aggregator), it's a redundancy to validate latter ones since in the end, attestation and proof db has attestation root as key

+ we should create TreeBacked value for gossip AggregateAndProof since we need to do `struct_hashTreeRoot` in a couple of places (`getAggregateAndProofSignatureSet`, `getIndexedAttestationSignatureSet` and `AggregateAndProofRepository.add`)

+ no other heavy operations except for signature verification, it's just too many aggregate and proof to validate
<img width="1336" alt="Screen Shot 2021-04-06 at 10 19 52" src="https://user-images.githubusercontent.com/10568965/113654269-a7066200-96c1-11eb-803d-d88d77209609.png">



[prater_validate_aggregate_attestation_0405.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/6261764/prater_validate_aggregate_attestation_0405.cpuprofile.zip)

**Comment by dapplion** [comment]
Already addressed with https://github.com/ChainSafe/lodestar/pull/2760 and https://github.com/ChainSafe/lodestar/pull/2801
