### ISSUE TITLE
`--private` mode CLI option to not send impl details

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2438]
**Is your feature request related to a problem? Please describe.**

I noticed Lighthouse has a `--private` option in their CLI that prevents client info from being sent over the identity protocol.  Maybe if we do this too it would be nice to have.

**Describe alternatives you've considered**

**Additional context**

**Comment by dapplion** [comment]
What's the usecase for that flag, when you don't want gossip, for local only testnets?

**Comment by 3xtr4t3rr3str14l** [comment]
> What's the usecase for that flag, when you don't want gossip, for local only testnets?

I think it's for not sending agent info across the network (client type, version, etc)

**Comment by 3xtr4t3rr3str14l** [comment]
But yeah not sure of a specific use case other than just someone not wanting to have that info sent out to minimize potentially identifying info.

**Comment by philknows** [comment]
Latest discussion points from @wemeetagain :

Use case would be similar to setting a blank graffiti, ie if you're paranoid about getting identified, attacked w lodestar-specific attacks.
1. attacker learns about lodestar DoS
2. attacker scans thru the network, connecting and running identify on all
3. attacker builds list of lodestar nodes
4. attacker executes attack on all lodestar nodes
Issue is a bit misworded since the user agent is part of the identify protocol, not part of gossipsub
Imo still useful but low priority
