### ISSUE TITLE
In ReqResp block method stream bytes from db

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2490]
**Describe the bug**

Right now when serving ReqResp block methods we read from DB, deserialize from bytes to struct and then re-serialize to send over the wire.

**Expected behavior**

We could just serve the bytes stream directly from db, prevent any serdes and require no memory.

**Comment by twoeths** [comment]
today I got this performance issue after restarting server 0, gossip blocks are processed >4s after the slot start frequently, sometimes it's up to 30s. It turns out that it takes 20% of our cpu just to serve beacon_blocks_by_range for a single peer
<img width="535" alt="Screen Shot 2021-11-12 at 17 06 34" src="https://user-images.githubusercontent.com/10568965/141449378-f5b31442-cbb4-4972-be47-4f7a1651e2ce.png">

<img width="1461" alt="Screen Shot 2021-11-12 at 17 07 10" src="https://user-images.githubusercontent.com/10568965/141449443-10e46311-4504-473f-a791-888dd1170081.png">


[1112_contabo_0_bad_perf.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/7526722/1112_contabo_0_bad_perf.cpuprofile.zip)
