### ISSUE TITLE
Wrong config in CLI dev cmd

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2594]
**Describe the bug**

Running the `dev` command in the CLI with `--minimal` I got 12 seconds per slot. Something is wrong the the config generation.

**Expected behavior**

Minimal should have 6 seconds per slot.

**Comment by q9f** [comment]
I also noticed that and traced through the code realizing that the presets are always overwritten by networks and none of the networks uses the minimal configuration, so even the default node options use a mainnet preset, therefore overriding any attempt to use a minimal preset.

That said, it might be worth refactoring the entire preset/network logic because there is literally no reason to use a network without a preset. we can keep the presets as templates but no longer expose them to the users and rather just reference them internally for the various networks.

easiest path of action would be to create a `dev` network that uses `minimal` to avoid falling back to default values. that said, I'm not entirely sure how involved this would be and would be happy to get a 2nd opinion on that.

**Comment by dapplion** [comment]
> I also noticed that and traced through the code realizing that the presets are always overwritten by networks and none of the networks uses the minimal configuration, so even the default node options use a mainnet preset, therefore overriding any attempt to use a minimal preset.
> 
> That said, it might be worth refactoring the entire preset/network logic because there is literally no reason to use a network without a preset. we can keep the presets as templates but no longer expose them to the users and rather just reference them internally for the various networks.
> 
> easiest path of action would be to create a `dev` network that uses `minimal` to avoid falling back to default values. that said, I'm not entirely sure how involved this would be and would be happy to get a 2nd opinion on that.

+1 to remove the preset option. Adding a dev dedicated network is a great idea too. We already craft the db paths of the dev command as if the network was "dev"
