### ISSUE TITLE
Ensure buffers are compatible in the browser

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/lodestar#26]
Since we wish to both use the Node Buffer type and attempt to maintain in browser compatibility we must make sure we have a method for achieving both these goals. It appears that if we use browserify and this library: https://github.com/feross/buffer we should be able to achieve this with little difficulty.

**Comment by Mikerah** [comment]
Finally some internal engagement. 

Anyway, we should create a separate issue in order to discuss using bignumber.js in addition to buffers or not using buffers at all and just using bignumber.js. The bignumber.js library supports endianess for numbers and let's us convert to a buffer array later on. I think we should do some benchmarking in order to decide since it would also affect the ssz library.

**Comment by GregTheGreek** [comment]
Related to #35
