### ISSUE TITLE
Improve forkchoice updateHead

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2747]
**Describe the bug**

This is from a prater node with no validator
<img width="1275" alt="Screen Shot 2021-06-24 at 09 00 35" src="https://user-images.githubusercontent.com/10568965/123191016-c47de780-d4ca-11eb-9205-86772410adf3.png">
[0624_prater_forkchoice_updateHead.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/6705773/0624_prater_forkchoice_updateHead.cpuprofile.zip)

a normal state transition takes 227.6m, 212.2 ms is for `updateHead` 

We need to find a way to improve `computeDeltas` in forkchoice implementation.

**Expected behavior**

Not sure what the expectation is but I think forkchoice is designed to be lightweight, taking 90% of time per normal state transition for forkchoice is too much.

**Comment by twoeths** [comment]
I think one of the cost is the slowness of BigInt calculation in `computeDeltas`. One idea is to track `effectiveBalance` as number instead of BigInt since `MAX_EFFECTIVE_BALANCE=32000000000` which is still in the range of number.

We need to write benchmark test for any solutions we want to go.

**Comment by dapplion** [comment]
Related https://github.com/ChainSafe/lodestar/issues/2455

**Comment by g11tech** [comment]
@dapplion assign pls

**Comment by dapplion** [comment]
![Screenshot from 2021-07-06 18-54-40](https://user-images.githubusercontent.com/35266934/124638810-b1382800-de8b-11eb-9563-f6217a01d19b.png)
![Screenshot from 2021-07-06 18-54-50](https://user-images.githubusercontent.com/35266934/124638814-b301eb80-de8b-11eb-9e89-6ed34bcbc939.png)

After implementing head caching fork-choice runs take 0.5% of CPU time in a not overloaded node (no subnets). Worth to look into it but not an high priority.

Also note that metrics reads match what Tuyen got in the profile.

**Comment by twoeths** [comment]
As noted in #2332, effectiveBalance is always multiple of  `EFFECTIVE_BALANCE_INCREMENT` so ideally we want to track the weight as `32, 31, 30` instead of `32000000000, 31000000000, 30000000000`

**Comment by dapplion** [comment]
Current metrics the fork-choice cost is very low :+1:

**Comment by dapplion** [comment]
Fork-choice updateHead cost is about ~1% of total CPU time currently. I think it can still be improved, but it's low priority

**Comment by dapplion** [comment]
Below is a CPU profile of running updateHead() in a loop inside a benchmark
![image](https://github.com/ChainSafe/lodestar/assets/35266934/8060463d-863a-45a1-8314-e2a3a7fe643e)

As shown in other profiles it's clear than the vast majority of time is spent on computeDeltas. The below percentages are likely wrong since for some reason the stack traces appear as the stack frame bounces from updateHead to updateHead/computeDeltas. 

![image](https://github.com/ChainSafe/lodestar/assets/35266934/fbc778a9-e1a1-479e-ad48-c2de937e62a8)

Reviewing computeDeltas, it's a pretty simple function:
- Loop over votes
- for each vote resolve what's voting to and add / substract its weight from those nodes

**Comment by twoeths** [comment]
closing via https://github.com/ChainSafe/lodestar/pull/5882
