### ISSUE TITLE
Refactor database files

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#308]
Database beacon api file is huge and it will keep growing, we need to split it into modules ideally without braking api.

https://github.com/ChainSafe/lodestar/blob/master/src/db/api/beacon/beacon.ts

**Comment by mpetrunic** [comment]
I would maybe go and break api similar to OpPool. We could introduce Repository pattern with crud methods (you would pass encodeKey callback to parent constructor).

**Comment by wemeetagain** [comment]
Some of the items stored in the db are nicely separable (eg: deposits, merkle tree, etc).
I think there may be some trickiness w/ blocks/states since there is more overlap eg setChainHeadRoots deals with both blocks and states.

We're also storing some "well known" roots, which we transparently fetch in eg: getFinalizedState, which does a Key -> root lookup, then root -> state lookup. My thought was that eventually we would have a wrapper caching layer that would store/fetch the "well known" things from memory and avoid the double-lookup.

This is all just fyi.

**Comment by mpetrunic** [comment]
well, you could either keep those methods in root beacon db api class or create some util module that gets required db modules in constructor
