### ISSUE TITLE
Gitcoin Grants link is 404

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#3136]
should be updated in `FUNDING.yml`

**Comment by philknows** [comment]
@dapplion 
https://gitcoin.co/grants/3512/chainsafe-lodestar-typescript-eth-beacon-chain-et

Although I cannot edit this specific grant above for some reason, it is currently disabled and not able to take in any grant money but is still searchable on Gitcoin. Is this sufficient for the publicity aspect of being listed on Gitcoin? I don't believe anybody can send money to it so we don't need to worry about any donations. If it is sufficient, I can edit our ./github/FUNDING.yml file to update the link in our Lodestar repo OR we can get rid of this file altogether because the current link leads to a 404.

**Comment by dapplion** [comment]
> I can edit our ./github/FUNDING.yml file to update the link in our Lodestar repo OR we can get rid of this file altogether because the current link leads to a 404

That sounds better than a 404
