### ISSUE TITLE
Support password file in account validator import

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3688]
For command `account validator import` allow to pass password as a file path, and ensure it's not interactive.

Additional:
- Review other account commands and provide options to prevent interactive mode

**Comment by philknows** [comment]
Adding note that this feature is required for the Wagyu Installer being worked on by Yodrick.

**Comment by dadepo** [comment]
@dapplion 

> Review other account commands and provide options to prevent interactive mode

I reviewed some of the other commands and there are options to prevent interactive mode. The only flow that is still interactive is the confirmation for voluntary exist. I opt to leave that as is, and not modify to have a non-interactive flow because of the magnitude of the action of exiting a validator. 

Do let me know if you still prefer to have that also be non-interactive.
