### ISSUE TITLE
BLS Pool Size

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3822]
**Describe the bug**

Currently BLS pool size is `number of cores`. I think it should `number of cores - 1` as we use 1 for the main thread

Also BLS pool size seems to be always 4
+ On contabo-20, it's really 4: `cpu cores	: 4`
+ But on hetzner-test0 it's 6: `cpu cores	: 6`

(checked with `cat /proc/cpuinfo | grep "cores"`)

**Comment by dapplion** [comment]
It doesn't really matter too much because in practice seems that only the first 2 workers take all the work. You can't really control on which core each worker will run really.

![Screenshot from 2022-03-03 15-15-26](https://user-images.githubusercontent.com/35266934/156539251-6dfb617c-26ef-4751-9e36-473df730efa9.png)

Also node-exporter shows that load is very evenly distributed across cores

![Screenshot from 2022-03-03 15-17-50](https://user-images.githubusercontent.com/35266934/156539596-e53f3c41-4159-4c1a-adc5-fe42fe4f28ba.png)

**Comment by dapplion** [comment]
I don't believe this is an issue. NodeJS native worker pool is always 4. Modern CPU can handle this mismatch in count just fine. We could worry about the extra overhead of more workers than necessary but it's a minor issue
