### ISSUE TITLE
[Prater] Late gossip blocks received

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4244]
**Describe the bug**

This is monitored in Prater nodes

<img width="800" alt="Screen Shot 2022-07-06 at 14 03 23" src="https://user-images.githubusercontent.com/10568965/177489593-33d7f2b3-753a-4b8e-87cb-7afbacb8eb8f.png">

This only happens in prater, I don't see this issue in mainnet and Ropsten

**Expected behavior**

No late block received

**Steps to Reproduce**

Run Prater

**Comment by dapplion** [comment]
@tuyennhv While investigating this issues is valuable this type of issues usually stay open in the Lodestar for a very long time. To organize this better I would suggest:
- Have some way to group this type of issues: one parent issue that links of this type of no-immediate-action-issues, and / or a label
- Try to gather more info locally, or spent some time investigating the issue
- Figure out what would be next steps to tackle the issue

If the purpose of this issue is only to journal odd behaviour we should have some way to check if this is Lodestar specific of from a network only. For this you could:
- Contrast with each prater node this metric. Are all nodes affected? Only this one? Why?
- Run other non-Lodestar nodes in Prater to contract findings

**Comment by philknows** [comment]
Based on `v1.1.0` metrics, this doesn't seem to be an issue anymore. We're seeing ~1 sec range now @tuyennhv . Feel free to close if agreed.
<img width="801" alt="Screen Shot 2022-09-23 at 3 06 46 AM" src="https://user-images.githubusercontent.com/58080811/191908302-5f10b193-4007-483f-8155-1d835c17c1d5.png">

**Comment by twoeths** [comment]
It's still an issue in Goerli from what I see, this is from a stable node (5 first days with v1.0.0 and 2 last days with v1.1.0, they are the same)

<img width="1203" alt="Screen Shot 2022-09-26 at 08 41 19" src="https://user-images.githubusercontent.com/10568965/192177640-24950d3e-591c-4557-9c70-d69d8cc88a3d.png">


It's better on mainnet nodes

<img width="1247" alt="Screen Shot 2022-09-26 at 08 40 01" src="https://user-images.githubusercontent.com/10568965/192177553-505c38ca-f011-48eb-a683-f421acbfb7db.png">

**Comment by dapplion** [comment]
@tuyennhv Can you plot block times with an histogram like here? It will illustrate better the distribution https://twitter.com/dapplion/status/1575431858522886144

**Comment by twoeths** [comment]
not an issue anymore since v1.2.0, below is 10m rate interval on the stable 1k node:

<img width="1269" alt="Screen Shot 2022-12-21 at 05 36 34" src="https://user-images.githubusercontent.com/10568965/208779976-ccb812e1-bac0-4093-8349-e65597caf6aa.png">
