### ISSUE TITLE
Publish-stable workflow bug

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4265]
**Describe the bug**

Publish-stable workflow ran to completion when tagging v0.40.0-rc.0.
See https://github.com/ChainSafe/lodestar/actions/runs/2632158460

**Expected behavior**

The workflow should stop when `is_stable` is determined to be false

**Comment by dadepo** [comment]
Run down of events that can help with the tracking down the root cause:

Here is the run down of events:

Earlier on, after running the `release:create-rc` script, I attempted the `release:tag-rc`. The output from the terminal was:

```
➜  lodestar git:(rc/v0.40.0) yarn release:tag-rc 0.40.0 57d13e1
yarn run v1.22.19
$ node scripts/release/tag_rc.mjs 0.40.0 57d13e1
Checking if branch rc/v0.40.0 exists in remote
Checking if tag v0.40.0-rc.0 exists in remote

Tag: v0.40.0-rc.0
Selected commit: 57d13e1d9d

commit 57d13e1d9d8f9cece6b3b11c1c9b61f98053535a
Author: Lion - dapplion <35266934+dapplion@users.noreply.github.com>
Date:   11 hours ago

    Fix typo in publish-dev.yml (#4256)

? Do you want to publish v0.40.0-rc.0 at commit 57d13e1d9d? Yes
```

A part of the CI failed as can be seen here: https://github.com/ChainSafe/lodestar/runs/7240784623?check_suite_focus=true

This was due to the fact that the `57d13e1` commit was for the create-rc. So deleted the tags and ran it again but this time, using the `a171ba0e` from the rc branch that was created.

This was ran `10:27 pm`  I have the time, because I sent a message to Cayman, I was going to try it again. The output from the terminal was:

```
➜  lodestar git:(rc/v0.40.0) yarn release:tag-rc 0.40.0 a171ba0e
yarn run v1.22.19
$ node scripts/release/tag_rc.mjs 0.40.0 a171ba0e
Checking if branch rc/v0.40.0 exists in remote
Checking if tag v0.40.0-rc.0 exists in remote

Tag: v0.40.0-rc.0
Selected commit: a171ba0e6c

commit a171ba0e6cc76b3774d06d96649e776652d0bedc
Author: Dadepo Aderemi <dadepo@gmail.com>
Date:   45 minutes ago

    v0.40.0

? Do you want to publish v0.40.0-rc.0 at commit a171ba0e6c? Yes
✨  Done in 8.06s.
```

Then later on, it was seen that at 10:28pm, the stable release job was triggered https://github.com/ChainSafe/lodestar/actions/runs/2632158460
