### ISSUE TITLE
Lodestar produced block with invalid attestation during Sepolia instability

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4333]
Post merge Sepolia has 2 unstable epochs

- the first merge slot was https://sepolia.beaconcha.in/block/115193
- Up until slot 115232, we don't see any of the config issue related validators missing a single slot. 115233 however is missed by lodestar and subsequently 115234&115235 are also missed by Besu and Nimbus. These are providers where no config issue is known, hence it could be a shuffling issue or something else
- The trigger point could be slot 115233, see slot dump from Nimbus node [invalid.tar.gz](https://github.com/ChainSafe/lodestar/files/9150536/invalid.tar.gz)
- Teku also logged that invalid slot. They failed validating the signature but the proposer_index matches the expected one (709) according to beaconcha.in [115233.zip](https://github.com/ChainSafe/lodestar/files/9150573/115233.zip)
- Seems like the block contains an attestation with invalid signature [state_at_115232.ssz.zip](https://github.com/ChainSafe/lodestar/files/9150582/state_at_115232.ssz.zip)
- The offending attestation is
```
IndexedAttestation{attesting_indices=SszList{size=17: 50, 198, 311, 389, 556, 639, 804, 1121, 1238, 1324, 1435, 1448, 1487, 1497, 1612, 1640, 1779}, data=AttestationData{slot=115232, index=0, beacon_block_root=0xacd63ca2b12641cb281fe40a479a5bf37debbba9ae324e4c9089742fdbbe1403, source=Checkpoint{epoch=3599, root=0x5a4b89da91bfe310be27b6cccaf4ead3ec62280d1ed9f4356e6df525a1f2d19b}, target=Checkpoint{epoch=3601, root=0xacd63ca2b12641cb281fe40a479a5bf37debbba9ae324e4c9089742fdbbe1403}}, signature=SszByteVector{0x86330d22c822f54c36456a82420ec64150024016a9ca1dd59218cec47d4d0be8182dbad6eacfff6debecd9ab2c7390840321416e0cb7ce01e6428ddef73f2777ca69e7d7fe448fc1febd86c6bff4d8a509bc29a3ec32e19e3f79aee8661c30ff}}
```
- source is correct, the target is weird. And gap between source and target is a couple of epochs. Source pre-merge and target post-merge.

**Hypothesis**
- attestation is valid wrt side chain and makes it into pool
- beacon node produces block on mainchain (with divergent shuffling) and pulls thsi attestation from the pool (because it was pre-validated)
- block is invalid because bitfield represents side-chain shuffling and is invalid to the assumed mainchain shuffling in the block

_continue_
- the gap 3599-3601 is present in other attestations https://sepolia.beaconcha.in/epoch/3601 - the target root is wrong
- But it might be correct wrt to the side chain, which the node had blocks available at the time
- The gap here at the point merge implies that there was still agreement in latest finalized and thus the source correct and thus lodestar still importing side-chain blocks

**Comment by twoeths** [comment]
The hypothesis is correct, the weird block `0xacd63ca2b12641cb281fe40a479a5bf37debbba9ae324e4c9089742fdbbe1403` happened in attestations of block slot 115225 to 115231 as head root. From https://sepolia.beaconcha.in/ I suppose:

<img width="818" alt="Screen Shot 2022-07-21 at 20 11 02" src="https://user-images.githubusercontent.com/10568965/180221659-454a06f3-13ff-4cd0-a9d6-3156118eb2ca.png">


- Note that slot 115224 does not pass the main branch checkpoint (115200), common ancestor is 115192
- At epoch 3600, some validators voted for 115224 as head and their attestations are valid because attester dependent root is last slot of epoch 3598 (same shuffling to main branch)
- At epoch 3601, some validators voted for 115224 as head, it passes gossip validation because we use state 115224 to verify. However attester dependent root (slot 115199) is different to main branch (different shuffling to main branch), i.e if we use head state to validate these attestations, signature verification would failed.
- At slot 115233 (epoch 3601), we produced block and include this conflicted attestation


**Note**
- According to the spec https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#attestations : `Up to MAX_ATTESTATIONS, aggregate attestations can be included in the block. The attestations added must satisfy the verification conditions found in [attestation processing](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#attestations)`

**Comment by dapplion** [comment]
@tuyennhv so is there any issue that causes this block to be valid with respect to Lodestar and invalid to other network participants?

**Comment by twoeths** [comment]
> @tuyennhv so is there any issue that causes this block to be valid with respect to Lodestar and invalid to other network participants?

no, lodestar is compatible to other clients. In the example above the produced block is not valid even to lodestar. Before bundling an attestation into block, we need to validate the signature of attestation. But since we did it in gossip validation function, we only need to make sure the shuffling of attestation is compatible to the state used to produce block.
