### ISSUE TITLE
Interop Issues

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#443]
Dump traces/logs/comments/etc here

**Comment by mpetrunic** [comment]
Those wierd block errors happens when something happens to state.currentJustifiedCheckpoint.

Error orginates: 
 at processAttestation (/home/mpetrunic/projects/eth2/lodestar/packages/lodestar/src/chain/stateTransition/block/operations/attestation.ts:47:5)

My  best guess is that it happens if you produce attestation just before next epoch gets finalized/justified and you are suppose to attest to new one not old one

**Comment by mpetrunic** [comment]
interop done
