### ISSUE TITLE
Update outdated NPM dependencies

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4431]
This issue is to track dependencies which are outdated and fixes are available for implementation. The following `lodestar-cli` dependencies are outdated:

- [ ] `ini`: Latest is `v3.0.0` https://www.npmjs.com/package/ini
- [x] `minimist`: Latest is `v1.2.6` https://www.npmjs.com/package/minimist
- [ ] `node-forge`: Latest is `v1.3.1` https://www.npmjs.com/package/node-forge
- [x] `tar`: Latest is `v6.1.1` https://www.npmjs.com/package/tar

**Comment by dapplion** [comment]
- `ini`, `minimist`, `tar`: Fixable by recreating yarn.lock
- `node-forge`: Dependency of libp2p-crypto, blocked until https://github.com/ChainSafe/lodestar/pull/4427

Other old packages there because:
- Our own dependency on "electron": "^19.0.9", @nazarhussain why not v20?
- typedoc: to be removed with https://github.com/ChainSafe/lodestar/pull/4436

**Comment by nazarhussain** [comment]
The `node-forge` will be updated once `@chainsafe/discv5`, `peer-id` and `libp2p` is updated to latest versions.

**Comment by nazarhussain** [comment]
The `ini` package is deep dependency of `lerna`, so no need to update.

**Comment by nazarhussain** [comment]
All other critical dependencies are fixed in the PR https://github.com/ChainSafe/lodestar/pull/4597

**Comment by nazarhussain** [comment]
Still WIP.

**Comment by philknows** [comment]
@nazarhussain Is there still a need to keep this specific issue open based on the comments and PRs above?

**Comment by nazarhussain** [comment]
We can close this issue.
