### ISSUE TITLE
Consider using alternative blake library

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#45]
The current library in the repo only supports 32 bytes and the spec requires a 64 bytes output

The following library seems to support 64 bytes and is in WASM :) https://github.com/nazar-pc/blake2.wasm

**Comment by Mikerah** [comment]
Yeah, the blake2 library in use was from way back when the spec just came out.

I see 2 sides of this: write our own in typescript/wasm and get it audited. Note that writing a safe hash function library is no joke but I'm up for the challenge. Or, use the one thay @gregthegreek suggest that appears to be un-audited at the moment. It would be great to minimize the amount of external dependencies since it makes it easier to audit + we don't need to worry about licensing.

**Comment by GregTheGreek** [comment]
If im not mistaken we're not using blake at all? I'll look for the reference

**Comment by GregTheGreek** [comment]
Yep: https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#hash
We've moved to keccak . Will close all blake related materials.
