### ISSUE TITLE
Lodestar does not add UDP to ENR

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4623]
**Describe the bug**

Jorge from Netheremind got the ENR from Lodestar shortly after start-up and the ENR did not had a UDP port.

**Expected behavior**

Add UDP port to ENR on startup from configured --port flag

**Comment by twoeths** [comment]
refer to https://github.com/ChainSafe/lodestar/pull/4579

the blocker for this issue is https://github.com/ChainSafe/discv5/issues/201

cc @wemeetagain

**Comment by twoeths** [comment]
if we set UDP to ENR, most of our peers are inbound
- this branch
<img width="1304" alt="Screen Shot 2023-01-07 at 15 08 21" src="https://user-images.githubusercontent.com/10568965/211140722-6fa65e48-15ac-4945-8274-a709f7383e30.png">

- unstable
<img width="1269" alt="Screen Shot 2023-01-07 at 15 08 52" src="https://user-images.githubusercontent.com/10568965/211140741-012c5352-fef3-410c-8ed7-f8dac712b2da.png">

we received/sent ways more goodbye requests from/to peers
- this branch
<img width="1264" alt="Screen Shot 2023-01-07 at 15 10 40" src="https://user-images.githubusercontent.com/10568965/211140796-72506636-406e-4052-a466-88f26acf173f.png">
<img width="1270" alt="Screen Shot 2023-01-07 at 15 11 01" src="https://user-images.githubusercontent.com/10568965/211140809-8d394865-6586-46b7-9c03-6821c526e7d6.png">

- unstable
<img width="1273" alt="Screen Shot 2023-01-07 at 15 11 47" src="https://user-images.githubusercontent.com/10568965/211140836-d09f79b1-7948-4413-b0b9-06964aa9d5a6.png">
<img width="1275" alt="Screen Shot 2023-01-07 at 15 13 58" src="https://user-images.githubusercontent.com/10568965/211140925-7ef817ae-1817-4e49-a702-b8a5d1005588.png">

lodestar tends to switch peers a lot with this branch, this is peer connection length
- this branch
<img width="1287" alt="Screen Shot 2023-01-07 at 15 33 32" src="https://user-images.githubusercontent.com/10568965/211141560-a806387d-7bf3-4024-8de8-42c929233b3c.png">

- unstable
<img width="1302" alt="Screen Shot 2023-01-07 at 15 33 59" src="https://user-images.githubusercontent.com/10568965/211141590-24f41bd4-1fb6-422f-adf6-3e1f947bea66.png">

although it switches peers a lot, the long lived subnet is worse
- this branch
<img width="1293" alt="Screen Shot 2023-01-07 at 15 37 09" src="https://user-images.githubusercontent.com/10568965/211141754-c410e552-0732-4d83-868b-005d5fbe67ca.png">

- unstable
<img width="1274" alt="Screen Shot 2023-01-07 at 15 37 46" src="https://user-images.githubusercontent.com/10568965/211141801-bdc38b02-f56b-4c49-b58d-e907e846d52b.png">

number of peers are usually 55 instead of 50 as in unstable
- this branch
<img width="1275" alt="Screen Shot 2023-01-07 at 15 42 39" src="https://user-images.githubusercontent.com/10568965/211141981-ead00ec8-0fec-49a1-ac6d-7b65279fe41d.png">

- unstable
<img width="1280" alt="Screen Shot 2023-01-07 at 15 43 11" src="https://user-images.githubusercontent.com/10568965/211141996-0c0344fa-334c-4959-a040-acdc2202adb1.png">

there's really an issue of peer management at lodestar side

**Comment by twoeths** [comment]
the issue with having too many peers (>55) is lodestar doesn't control which peers to remove, it's decided randomly by libp2p https://github.com/libp2p/js-libp2p/blob/v0.39.2/src/connection-manager/index.ts#L635 since we don't have any tagging strategy. It does not happen with `unstable/stable` branch because peers are consistently at 50. When peers are >50 but <= 55, it's decided by lodestar's pruning strategy.

also lodestar could consider more outbound peers, right now the ratio is 0.1 in lodestar (`OUTBOUND_PEERS_RATIO`) while lighthouse (`TARGET_OUTBOUND_ONLY_FACTOR`) is 0.3

**Comment by twoeths** [comment]
The memory leak issue also happens with unstable/stable (v1.3.0). Setting udp to enr makes it happen consistently

This is from stable (v1.3.0) 1k validators:
<img width="802" alt="Screen Shot 2023-01-13 at 09 34 59" src="https://user-images.githubusercontent.com/10568965/212223976-efd1734b-edf7-4f53-8256-fe1b883aa2a1.png">

This really correlate to `beacon_blocks_by_range`, `beacon_blocks_by_root`, `status` incoming requests

<img width="1276" alt="Screen Shot 2023-01-13 at 09 38 40" src="https://user-images.githubusercontent.com/10568965/212224523-aca125a4-a49a-496d-bb68-839f77fe596f.png">

<img width="1273" alt="Screen Shot 2023-01-13 at 09 38 53" src="https://user-images.githubusercontent.com/10568965/212224559-cbd93c99-9f56-4020-b71e-2bb0dee0464d.png">

<img width="1292" alt="Screen Shot 2023-01-13 at 09 39 04" src="https://user-images.githubusercontent.com/10568965/212224584-208d5e05-cc13-43be-8bc3-09eb700a07b4.png">


I notice that it does not happen with other stable nodes.

**Comment by wemeetagain** [comment]
I think that strange behavior on stable-lg1k happened because it ran out of disk space, then some disk space was freed, all without a process reboot. I've noticed whenever this happens, there's a huge spike in peer count and behavior is really unpredictable. On process reboot, behavior returns to normal.
