### ISSUE TITLE
Docker deployment vs source deployment

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4727]
**Describe the bug**

I switched form a v1.2.0-rc.3 github deployment to docker:

- Better validator performance

<img width="815" alt="Screen Shot 2022-11-06 at 14 25 11" src="https://user-images.githubusercontent.com/10568965/200159174-6292f714-9c24-4228-bf08-4defa30e033c.png">

- Better gossip attestation validation

<img width="812" alt="Screen Shot 2022-11-06 at 14 25 53" src="https://user-images.githubusercontent.com/10568965/200159197-f7c820bc-b92f-4861-82ca-13b6e9f4a9e6.png">

- Could be due to better BLS's performance

<img width="807" alt="Screen Shot 2022-11-06 at 14 27 24" src="https://user-images.githubusercontent.com/10568965/200159258-00db8a94-e961-4eb3-8a10-79c11dbd8fbd.png">

- Less dropped messages

<img width="782" alt="Screen Shot 2022-11-06 at 14 26 31" src="https://user-images.githubusercontent.com/10568965/200159219-1b4384e2-75db-4d9d-b7b4-cb0b0cf13ec4.png">

- Less time  / more stable epoch transition

<img width="1207" alt="Screen Shot 2022-11-06 at 14 37 08" src="https://user-images.githubusercontent.com/10568965/200159526-aa9127ac-f7e4-47f9-8007-97db229393f3.png">

**Expected behavior**

Performance between 2 types of deployment should be the same

**Comment by dapplion** [comment]
Would need much more data to claim significant performance differences between bare metal and docker performance. In theory bare metal must be >= docker, unless some issue with compiled native dependencies. If that's the case we should benchmark how blst-ts pre-builds performs in different enviornments, instead of measuring overall performance which can be affected by many other variables.

Closing for now, if relevant the issue should be continued as "blst-ts pre-build performance across environments"
