### ISSUE TITLE
Installation fails macOS Ventura 13.0.1 version

### ISSUE THREAD

**Issue by AmanRaj1608** [ChainSafe/lodestar#4767]
**Describe the bug**

While installing and building on new macos version. This is due to the version of [blst-ts package](https://github.com/ChainSafe/blst-ts/issues/70)
Need to bump up from `@chainsafe/blst:^0.2.4` to  `@chainsafe/blst:^0.2.6`

**Expected behavior**
Should Install the packages and build.

**Steps to Reproduce**
- Clone project
- Install via `yarn install --ignore-optional`

**Screenshots**
![image](https://user-images.githubusercontent.com/42104907/201940574-8407e9b4-6328-43fb-b4f3-ae7df46ea892.png)

- OS:  OSX Ventura
- Version: 13.0.1
- Branch: stable / unstable
- Commit hash: 1ceaa20ebef7a7adcf9709c323b128d4b4fbeba6

**Comment by dapplion** [comment]
- Linking https://github.com/ChainSafe/blst-ts/issues/75

**Comment by wemeetagain** [comment]
@AmanRaj1608 can you retry with latest lodestar v1.4.2 ?

**Comment by patrickmao1** [comment]
looks like it's the good ol' "package for darwin-arm64 doesn't exist" issue? 
```
Retrieving BLST native bindings /Users/patrickmao/repos/lodestar/node_modules/@chainsafe/blst/prebuild/darwin-arm64-93-binding.node ...
Error: Error importing BLST native bindings: 404 Not Found
```
Where can I get this prebuild for darwin-arm64?

**Comment by dapplion** [comment]
> looks like it's the good ol' "package for darwin-arm64 doesn't exist" issue?
> 
> ```
> Retrieving BLST native bindings /Users/patrickmao/repos/lodestar/node_modules/@chainsafe/blst/prebuild/darwin-arm64-93-binding.node ...
> Error: Error importing BLST native bindings: 404 Not Found
> ```
> 
> Where can I get this prebuild for darwin-arm64?

We currently don't have the capability to provide darwin-arm64 prebuilds, see https://github.com/ChainSafe/blst-ts#supported-environments

**Comment by maschad** [comment]
> looks like it's the good ol' "package for darwin-arm64 doesn't exist" issue?
> 
> ```
> Retrieving BLST native bindings /Users/patrickmao/repos/lodestar/node_modules/@chainsafe/blst/prebuild/darwin-arm64-93-binding.node ...
> Error: Error importing BLST native bindings: 404 Not Found
> ```
> 
> Where can I get this prebuild for darwin-arm64?

You can find the supported environments [here](https://github.com/ChainSafe/blst-ts#supported-environments), which includes up to the [latest Long-Term Support build of Node - 18.14.2](https://nodejs.org/download/release/latest-v18.x/)

We have an issue for the current Node [raised](https://github.com/ChainSafe/blst-ts/issues/80) .

If you are still experiencing this issue, please ensure you have [python installed](https://github.com/ChainSafe/lodestar/issues/4971#issuecomment-1370931694) You can use [homebrew](https://docs.brew.sh/Homebrew-and-Python)

**Comment by maschad** [comment]
> looks like it's the good ol' "package for darwin-arm64 doesn't exist" issue?
> 
> ```
> Retrieving BLST native bindings /Users/patrickmao/repos/lodestar/node_modules/@chainsafe/blst/prebuild/darwin-arm64-93-binding.node ...
> Error: Error importing BLST native bindings: 404 Not Found
> ```
> 
> Where can I get this prebuild for darwin-arm64?

You should be able to get a `darwin-arm64` prebuild _depending on your OS version_ since [this fix](https://github.com/supranational/blst/issues/127#issuecomment-1235594657) upstream. We also released [that fix in  blst-ts v0.2.6 ](https://github.com/ChainSafe/blst-ts/issues/70#issuecomment-1238648474). We support up to the [latest Long-Term Support build of Node - 18.14.2](https://nodejs.org/download/release/latest-v18.x/) and we have an issue for the current Node [raised](https://github.com/ChainSafe/blst-ts/issues/80).

If you are still experiencing this issue, please ensure you have [python installed](https://github.com/ChainSafe/lodestar/issues/4971#issuecomment-1370931694).

**Comment by ankurdubey521** [comment]
Was facing the same issue, and creating a symlink called `python` pointing to the `python3` binary solved the issue for me.

**Comment by philknows** [comment]
Will close this issue with the solutions above working for most users. Feel free to re-open or create a new one if the above solutions no longer work.

**Comment by sergeyWh1te** [comment]
I confirm that it would be good to fix the script, where on mac os python is used instead of python3. In the meantime, this is not there, you can treat it like this:
<img width="860" alt="Screenshot 2023-07-18 at 21 05 43" src="https://github.com/ChainSafe/lodestar/assets/102730938/ca1b1804-830e-483e-9ee9-9e538f1eb8c0">

```bash
ln -s /opt/homebrew/bin/python3 /usr/local/bin/python
```

And happy hacking =)
