### ISSUE TITLE
Improve regular sync

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#483]
- regular sync should only be started after initial sync is done
- use events as this information might be useful to other parts of application
- if regular sync is more than n blocks behind, use blockByRange to catch up

**Comment by GregTheGreek** [comment]
Isn't this default behaviour [here](https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/sync/index.ts#L97)?

There may be an edge case, where the chain is lets say 9 months ahead at slot 10,000 (lol) and by the time we get to 10,000 the chain is at 15,000. 5000 block may be too much to regular sync, so an optimization would be to sync chunks (via get_blocks_by_range) from a bunch of different peers, put them in the queue (i believe the priority queue will handle this by default) and then wait until the queue finishes, then start regular sync.

Writing this i realized that its because of the queue, that regular sync starts... lol
We need to be notified when the priority queue is empty...

Also addressed by #479

**Comment by mpetrunic** [comment]
Yeah, sync needs to probably subscribe on processedBlock event so it can figure out on which slot our head is.

That said, initial sync assumes that is syncs only one valid chain so it can do stuff like header chain validation and quick state transition. In regular sync we need to keep track of all different chain versions(in case of fork). I don't see a reason for regular sync not to fetch blocks by range if it figures that it has to sync multiple blocks. Not sure how to proceed we cannot do initial sync after finalized epoch as we don't know which chain is real.

**Comment by mpetrunic** [comment]
unstale
