### ISSUE TITLE
v1.3.0: Failed to submit attestations due to insufficient peers

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5024]
**Describe the bug**

<img width="1294" alt="Screen Shot 2023-01-19 at 18 12 11" src="https://user-images.githubusercontent.com/10568965/213427846-4ed4bbcc-66fb-4316-a1f6-4eba1f778cc7.png">

this only happens since v1.3.0

the log:
```
Jan-19 10:43:38.374[]                ^[[34mdebug^[[39m: Request error, retrying routeId=submitPoolAttestations, baseUrl=http://65.109.31.200:9596 Internal Server Error: Multiple errors on submitPoolAttestations
PublishError.InsufficientPeers
PublishError.InsufficientPeers
Error: Internal Server Error: Multiple errors on submitPoolAttestations
PublishError.InsufficientPeers
PublishError.InsufficientPeers
    at HttpClient.requestWithBody (file:///usr/app/packages/api/src/utils/client/httpClient.ts:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Not sure if it happens with v1.4.0 since it mostly happens on mainnet nodes

**Expected behavior**

- No error

**Comment by twoeths** [comment]
`submitPoolAttestations` api of rescue node was called with same error

```
an-20 08:55:00.358[]                debug: Request error, retrying routeId=submitPoolSyncCommitteeSignatures, baseUrl=http://***:9596 Internal Server Error: PublishError.InsufficientPeers
```

usually the rescue node has no validator so there are not a lot of subnet peers, we should subscribe to all subnets there

**Comment by nflaig** [comment]
I think the root cause it really the peer count, I was using `v1.3.0` for a while now and had a lot of issues with missing attestations. I am not sure if it should be able to submit attestations if the peer count is close to or completely 0. For me the peer count issue seems to be fixed in `v1.1.1` and it did not miss a single attestations for 2 days now.

In comparison this is how the peer count metrics look


**v1.3.0**

![image](https://user-images.githubusercontent.com/38436224/214247274-c766a073-c486-4b38-a4fe-0ee2069fb610.png)


**v1.1.1**

![image](https://user-images.githubusercontent.com/38436224/214247581-6c12f05a-2048-499e-9fd0-9f7f1d6323a9.png)

**Comment by twoeths** [comment]
PeerCount has been stable in v1.4.0

<img width="1298" alt="Screen Shot 2023-02-03 at 09 17 52" src="https://user-images.githubusercontent.com/10568965/216496606-9c1066cd-942c-4f7a-9308-d36b67ba285a.png">

I don't see this `PublishError.InsufficientPeers` anymore after deploying v1.4.0 to mainnet nodes

**Comment by nflaig** [comment]
yes, also running v1.4.1 now and it looks good 🚀
