### ISSUE TITLE
Lodestar enagages all cores 100% when doing countdown for genesis

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#5224]
**Describe the bug**
When trying to run a lodestar interop locally, noticed that lodestar starts consuming 100% cpu on all cores
![image](https://user-images.githubusercontent.com/76567250/222251355-029c2ad7-2a1d-47f1-b0c8-5bfcb572238e.png)

which returns to normal as soon as genesis countdown is finished and chain starts moving.

Bug seems to be lodestar doing an active wait on some multi threaded workers

**Expected behavior**
Should not engage CPU cores while genesis countdown

**Steps to Reproduce**
run local interop and observe cpu usage while countdown to genesis
```
cd packages/beacon-node
EL_BINARY_DIR=g11tech/geth:withdrawalsfeb8 EL_SCRIPT_DIR=gethdocker yarn mocha test/sim/withdrawal-interop.test.ts
```

OS: ubuntu 22.04

**Comment by dapplion** [comment]
@g11tech Run locally and could recreate. Tho:
- Extending the genesis delay the 100% CPU only lasts for about 10 seconds, then goes back to idle. So your observation that it lasts for the entire genesis waiting period so happens that the waiting period is about 10 seconds
- I attached a CPU profiler and it was empty. There must be a bug or something so I can't tell what's taking CPU

Could geth CPU be reported as node's process since it is run a child process? I can't think of anything on start that could max out CPU. We only multithread BLS sig verification

**Comment by g11tech** [comment]
> @g11tech Run locally and could recreate. Tho:
> 
>     * Extending the genesis delay the 100% CPU only lasts for about 10 seconds, then goes back to idle. So your observation that it lasts for the entire genesis waiting period so happens that the waiting period is about 10 seconds
> 
>     * I attached a CPU profiler and it was empty. There must be a bug or something so I can't tell what's taking CPU
> 
> 
> Could geth CPU be reported as node's process since it is run a child process? I can't think of anything on start that could max out CPU. We only multithread BLS sig verification

hmm yes, it goes back to idle, but CPU during this 10 sec period scales with number of cpu cores (tested on 24 core) and all cores engaged there as well.

I will try running geth separately as see what happens

**Comment by g11tech** [comment]
@dapplion didn't notice with other EL clients so closing the issue as of now
