### ISSUE TITLE
Error using Lodestar as a failover

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#5323]
From discord (https://discord.com/channels/593655374469660673/743858262864167062/1090175408340733962):

I have a setup where a teku validator uses Lodestar as a failover.
![image](https://user-images.githubusercontent.com/1348242/228867643-937028ca-b220-429d-8af1-964a99a05dd8.png)

however when it tries to connect, Lodestar returns this error

**Comment by Chozowarrior** [comment]
also tested on Goerli with same results

**Comment by Chozowarrior** [comment]
The other way around. Teku as failover for Lodestar VC does work but does display some errors in the logging: 
![image](https://user-images.githubusercontent.com/43718356/232802482-da186c72-3e7f-4419-b430-dc99fac956e6.png)

**Comment by dapplion** [comment]
> The other way around. Teku as failover for Lodestar VC does work but does display some errors in the logging: ![image](https://user-images.githubusercontent.com/43718356/232802482-da186c72-3e7f-4419-b430-dc99fac956e6.png)

What version of Teku are you using? execution_optimistic should be implemented by all clients now

**Comment by Chozowarrior** [comment]
> > The other way around. Teku as failover for Lodestar VC does work but does display some errors in the logging: ![image](https://user-images.githubusercontent.com/43718356/232802482-da186c72-3e7f-4419-b430-dc99fac956e6.png)
> 
> What version of Teku are you using? execution_optimistic should be implemented by all clients now

yes the otherway around issue has been resolved but the main issue (Lodestar as failover for Teku has not been resolved yet).

**Comment by dapplion** [comment]
@Chozowarrior Could you share the version of the Teku beacon node that the Lodestar validator client of your screen capture? Then I can check with Teku devs to see if they are complying with the beacon API spec

**Comment by Chozowarrior** [comment]
> @Chozowarrior Could you share the version of the Teku beacon node that the Lodestar validator client of your screen capture? Then I can check with Teku devs to see if they are complying with the beacon API spec

You mean validator client right? I was using Teku 23.3.1 as a validator at the time. I was also in contact with the Teku team regarding this issue. since there was also a different issue on their side because after failing to connect to Lodestar it would not successfully attest after connecting to a different failover. That was this issue in case it is of any interest https://github.com/ConsenSys/teku/pull/7016 I was in contact with Stefan Bratanov regarding this.

**Comment by nflaig** [comment]
@Chozowarrior Are you still running Lodestar as a failover node with Teku VC? The errors you reported should be fixed now by https://github.com/ChainSafe/lodestar/pull/5722 and https://github.com/ChainSafe/lodestar/pull/5784 but those should not have caused actual issues (just noise). 

I am running Lodestar and Teku in a 1:1 setup which works great with the latest releases. Would be interesting to know if this issue is resolved by now. If you deploy from `unstable` branch the noisy eventstream errors should be gone too.

**Comment by Chozowarrior** [comment]
@nflaig yes I am still using Lodestar as a failover for some validators and as a primary for others as well. It is working for last month or so indeed so that is great. The behavior together with Teku only shows some errors that are maybe a bit overdone. The Teku dev told me the default behaviour is that the Teku-VC sends the attestations to the primary node plus all failover nodes to maximize the propogation. However this results in error messages on the Lodestar when the attestation has already been gossiped (see below). The behaviour in Nimbus which is a 2nd failover is different as this just blindly attests without the check that Lodestar seems to have.

However this issue is can indeed be closed but wonder whether the below is still interesting to look into as this error look messy, maybe info would be better here.

jul 21 23:01:25 ssay-NUC8i5BEH lodestar[1557]: Jul-21 23:01:25.336[api]             error: Error on submitPoolAttestations [0] slot=6929105, index=40 code=ATTESTATION_ERROR_ATTESTATION_ALREADY_KNOWN, targetEpoch=216534, validatorIndex=XXXX

**Comment by nflaig** [comment]
Thanks for the detailed answer. Great to hear that it works for you as well. Indeed, the error might be a bit annoying but as far as I know this does not cause any issues.

@tuyennhv wdyt? could we log this error with that specific code to debug instead?

**Comment by twoeths** [comment]
@nflaig I think we should implement `ignoreIfKnown` flag, it's to be `true` for api validation but `false` for gossip validation https://github.com/ChainSafe/lodestar/blob/325734518cf024869fb8a7d33cb75b665438a83b/packages/beacon-node/src/chain/validation/attestation.ts#L79

even when we use Lodestar as the primary node, submitted attestations can reach our node by gossip before the api since `vc` can published to fallback node already

**Comment by nflaig** [comment]
Closing as errors mentioned in this issue have been resolved https://github.com/ChainSafe/lodestar/issues/5323#issuecomment-1646283317.

The other error mentioned in https://github.com/ChainSafe/lodestar/issues/5323#issuecomment-1646283317 is tracked in a different issue.
- https://github.com/ChainSafe/lodestar/issues/6021
