### ISSUE TITLE
Track Missed blocks

### ISSUE THREAD

**Issue by maschad** [ChainSafe/lodestar#5343]
**Is your feature request related to a problem? Please describe.**

~~If a validator consistently misses blocks, their penalties will increase, and they may eventually be kicked out of the validator pool altogether. Therefore we want to track missed blocks.~~

We want to replicate the [beaconcha.in block chart](https://beaconcha.in/charts/blocks) for local validators.

**Describe the solution you'd like**

Following up from https://github.com/ChainSafe/lodestar/pull/5309  If a validator fails to propose or attest to a block at the appropriate time, it is considered a missed block. A missed block can occur for several reasons, and so we have to instrument all possible areas where it could occur. Such as Networking errors, failure to publish, failure during `processBlock`  or other bugs.

**Additional context**

Related to #5255

**Comment by dapplion** [comment]
Missing blocks does not incur any penalties on the validator. Only missing attestation and sync committee duties incur penalties which we already track. Regarding missed blocks
- failure to publish: already tracked
- failure during processBlock: already tracked
- Networking errors: not really possible to track since a single node has no visibility what happens on the rest of the network. The only data points you have are:
  - seeing the gossip message containing your block sent again to you; which does not say much since there could be a network partition and the block still not reach the next proposer
  - checking that the block is included in the chain after a sufficiently large re-org safe distance. This is what this metric intended to track https://github.com/ChainSafe/lodestar/issues/5255 basically means:
    - orphaned: network observer has **seen** the block but it's not included in the canonical chain
    - missed: network observer has **not seen** the block at all

**Comment by maschad** [comment]
> Missing blocks does not incur any penalties on the validator. Only missing attestation and sync committee duties incur penalties which we already track. 

Thanks for clarifying, chatGPT let me down here, should have crossed checked in [the knowledge base](https://kb.beaconcha.in/rewards-and-penalties#block-reward) 

> checking that the block is included in the chain after a sufficiently large re-org safe distance.

What would you define as a sufficiently large re-org distance? I suppose 7 blocks since that is the largest reorg to date.

> missed: network observer has not seen the block at all

Understood, I'll update that PR.

**Comment by nflaig** [comment]
> or attest to a block at the appropriate time

this is also not related to missed blocks, attestations are not done per block but per slot which might or might not a include block (`beacon_block_root`, LMD GHOST vote)

**Comment by philknows** [comment]
Resolved with #5538
