### ISSUE TITLE
Conventional commits usage and further definition

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5433]
This issue follows up on #1773 and recently merged #5342 for further defining usage of conventional commit structure specifically for our Lodestar monorepo.

Reference comment: https://github.com/ChainSafe/lodestar/pull/5419#pullrequestreview-1403626336

- Add structure: `type(scope?): subject` and brief explanations for each
- Define when to use each `type` 
- Should we advocate for using `scope` in every PR title? If yes, how? The github actions checker currently does not enforce this usage.
- Modify examples of PR titles with bullet points instead of quoting
- Define when and how to indicate breaking changes on commit level and further discuss how to display those in the Changelog which should be targeted towards non-developer user/operator of Lodestar. (see [comment](https://github.com/ChainSafe/lodestar/pull/5487#discussion_r1192302396))

**Comment by dapplion** [comment]
What's the purpose of (scope)? Having to pick a scope every time sounds annoying to me

**Comment by nflaig** [comment]
> What's the purpose of (scope)?

I think scope could be an easy way to give the commit more context, especially because Lodestar monorepo has several packages and subcategories

- gives more clarity on what part of the code was modified, meaning the commit message itself does not need to do that and can focus on the change being done
- makes commit easier filterable/searchable, would only work if this patterns is consistently applied
- depending on how we generate changelogs, most tools group by scope, this makes changelog easier to read
- generally, it should be easy to define a scope for most commits based on
   - package (or subcategory)
   - hard fork
   - EIP

The scope is not required by the PR title checker as discussed here https://github.com/ChainSafe/lodestar/pull/5342#discussion_r1158126144, so usage would be based on personal preference. For me, it sometimes makes it easier to convey all required information in the commit message.

**Comment by philknows** [comment]
Completed by #5342
