### ISSUE TITLE
Release Strategy

### ISSUE THREAD

**Issue by soc1c** [ChainSafe/lodestar#558]
- What's your current release strategy if any?
- Are there any releases yet?
- Where are you releasing, Github, externally?
- Are you using Gitflow (feature branches, release branches)?
- What's the master branch, what's alpha, what's 0.9.x?
- How can I help facilitating a release process?

ref #194 #181 #468

**Comment by wemeetagain** [comment]
:pray: Thanks for helping bump this, we're struggling w this right now.

- Current strategy
Manually publish to npm as versions get bumped, mainly due to breaking changes or wanting to use a package with another externally. We've been somewhat lacking in this, as latest published version has sometime fallen behind latest versions on github.

We hoped try moving to publishing in CI, so that if a new version was detected in any of our package.jsons, that new version would be published to npm.
Another idea we've been thinking about is switching to a single version for our monorepo packages, and upgrading them in lockstep w lerna.
Also, right now, creating a changelog would be a pretty painful process, it may be nice to experiment with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
- Are there releases yet?
We've published a bunch of our auxiliary / utility packages to npm, but we have no published _lodestar_ releases.
- Where are you releasing?
I think it would be great to release on github, with a changelog and 'github release' page. Currently we're more focused on publishing packages to npm.
- Are you using gitflow?
No, not currently. We mostly just have master. If there's a somewhat bigger feature, we'll create a branch for that (eg: 0.9.x upgrading to 0.9 of the spec).
- Whats master? whats alpha? whats 0.9.x?
master is most recent working version
alpha is a stale(?) branch
0.9.x is upgrading to 0.9.x of the spec
- How can I help facilitating a release process?
If you have any suggestions, love to hear them.
If you see anything here that you think you can fix, please do it. We'll be really thankful. :pray: 
If there are any low-hanging fruit we can do to make things more organized, I'd love to start there.

**Comment by ryanchristo** [comment]
> Another idea we've been thinking about is switching to a single version for our monorepo packages

Just to follow up on the discussion in Discourse, switching from independent package versions to lockstep versioning might make the release process easier.

Whenever you publish with lerna, each package that has changed within the monorepo will be bumped to the selected version and, if one of the packages within the monorepo depends on one of the packages getting bumped and published, that package will also be bumped and published.

Keep in mind each package that is published will be tagged with the same version number, so you would have to start with whatever the next version is for the package with the latest version in the monorepo.
