### ISSUE TITLE
Retrieving Wrong Slot

### ISSUE THREAD

**Issue by araskachoi** [ChainSafe/lodestar#5835]
### Describe the bug

When calling the api for beacon block, there is a one-off bug for the slot:

ex:
req:
```
curl -X 'GET' \
  '<IP>:<PORT>/eth/v1/beacon/blocks/2900001/attestations' \
  -H 'accept: application/json'
```
resp:
```
{"data":[{"aggregation_bits":"0xf7bf7abffffdef3f","data":{"slot":"2900000","index":"0","beacon_block_root":"0xa86af90be36050734820488d53ca34dd10adf905e47ad54112bacb17af32c5a8","source":{"epoch":"90624","root":"0xb7ad9f6f961336a2eae59fe283204a22c6126543804cab3273068768afdffa7e"},"target":{"epoch":"90625","root":"0xa86af90be36050734820488d53ca34dd10adf905e47ad54112bacb17af32c5a8"}},"signature":"0x91ee211c9672868eec4e9bb899a0b4885f2b7a4e8806820d2ef6fb719bc162726d13d8f5a9c8fc3c25a9824530a9caca03619aae8c9db25449bc5560fada18a22da808ae50cdc68e6f04cbaad832c7ee16848ebd75bdbd6bac45a56603ce5366"}],"execution_optimistic":false}
```

^as can be seen above, the slot i have provided is `2900001` but the slot returned is `2900000` in the data.slot field.

### Expected behavior

I would expect that the slot provided would be the slot returned. however, if this is expected behavior, then this issue ticket can be ignored and closed.

### Steps to reproduce

1. call open api endpoint of consensus client:
```
 curl -X 'GET' \
  '<IP>:<PORT>/eth/v1/beacon/blocks/2900001/attestations' \
  -H 'accept: application/json'
```

### Operating system

Linux

### Lodestar version or commit hash

v1.9.2/26fd079

**Comment by HiroyukiNaito** [comment]
You provided a block_id [2900001].
Please refer to "https://www.quicknode.com/docs/ethereum/eth-v1-beacon-blocks-block_id-attestations" .

Also, please refer to the documents.
This document may help you understand the difference between block id and slot number.
https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/attestations/

**Comment by nflaig** [comment]
@HiroyukiNaito This is not quite correct. The `block_id` can be one of: `"head" (canonical head in node's view), "genesis", "finalized", <slot>, <hex encoded blockRoot with 0x prefix>`, see https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockAttestations for further details. 
If you provide a number like 2900001 it will query for the block in the slot. To query for a specific block you have to provide the hex encoded block root with 0x prefix.

@araskachoi Regarding your issue, I need to check what the expected behavior is if the slot you query for does not have a block, I would expect that it should throw a "not found" error and not return the block of a previous slot. Returning data from another slot seems like a bug.

**Edit:** I was thinking for some reason the API you called is `/eth/v2/beacon/blocks/{block_id}` which should not give you a block of a different slot but will throw if the slot is empty. As Lion mentioned the block itself contains data like attestations with different slot numbers.

**Comment by dapplion** [comment]
Block `2900001` may includes attestations from any slot in the range `[2900001 - 1, 2900001 - 32]`. It is not possible for block at slot N to include attestations at slot N

**Comment by HiroyukiNaito** [comment]
@nflaig  Thanks for describing that! I understand.

**Comment by nflaig** [comment]
Closing as this is expected behavior, see https://github.com/ChainSafe/lodestar/issues/5835#issuecomment-1663913770
