### ISSUE TITLE
Error setting agentVersion for the peer

### ISSUE THREAD

**Issue by matthewkeil** [ChainSafe/lodestar#6365]
### Describe the bug

Reported by @nflaig in #6315 but is unrelated.  There is an issue with `metadata.get("AgentVersion") potentially or one of the other functions in https://github.com/ChainSafe/lodestar/blob/2eea2d60707a3bc5c150a7a0da261a8e7da079d1/packages/beacon-node/src/network/peers/peerManager.ts#L614-L619

### Expected behavior

Should not throw an error

### Additional context

```
Jan-17 09:17:23.039[network]         error: Error setting agentVersion for the peer peerId=16Uiu2HAmKpgbkNA2AKYvt4qfdwFsSwuM7NwE8aMMHoMJiCBAxKAL - NotFound: 
Error: NotFound: 
```

### Operating system

Linux

### Lodestar version or commit hash

v1.14.0-rc.1

**Comment by nflaig** [comment]
The error seems to be thrown here
https://github.com/ChainSafe/lodestar/blob/cbf349c73d7730c11d7295c27a61fbf36225df52/packages/beacon-node/src/network/peers/datastore.ts#L103-L104

I haven't seen this until recently, maybe it related to libp2p update

but we could also consider to log this to debug, doesn't seem to be a critical issue if we can't set the agent version due to peer not found
https://github.com/ChainSafe/lodestar/blob/cbf349c73d7730c11d7295c27a61fbf36225df52/packages/beacon-node/src/network/peers/peerManager.ts#L623

**Comment by matthewkeil** [comment]
Trying to sort out why this started to pop up all the sudden.  It is not a dependency that changed.  The error originates in leveldb here and is 11 years old...
https://github.com/Level/classic-level/blob/a21dfbfef088b159326a090d3585f080fbd0463f/deps/leveldb/leveldb-1.20/util/status.cc#L47-L48

And the surrounding code along the stream it percolates from has not changed either.  So it must be about how the timing of peers coming and going occurs.... digging some more to try and figure out why

**Comment by twoeths** [comment]
this could be the root cause https://github.com/ChainSafe/lodestar/issues/6382
