### ISSUE TITLE
Filter out non-viable branches when call to get_head 

### ISSUE THREAD

**Issue by ColinSchwarz** [ChainSafe/lodestar#637]
v0.9.3: filter out non-viable branches when call to get_head (ethereum/eth2.0-specs#1495)

**Comment by twoeths** [comment]
I suppose we have nothing to do with this because we use different algorithm.
+ According to the spec, we want to filter blocks before traverse them to getHead.
+ For our algorithm, we maintain `bestTarget` so we only get it in `head` (getHead). We don't traverse blocks so we don't need to filter.

can you confirm @wemeetagain ?

**Comment by twoeths** [comment]
I took some more time on this. The main point is to make sure the head has the same finalized & justified checkpoint to the store, so I propose:

+ Maintain justified/finalized checkpoint in all nodes
+ Whenever there is justified/finalized checkpoint change, we have to traverse from the justified checkpoint to decide new best target of every node (if needed)
+ On weight change, make sure the best target has same justified/finalized checkpoint to the store.

**Comment by twoeths** [comment]
On the other hand, if we do like that it may not be worth to follow our own specific algorithm compared to the spec because we have to do the traversal anyway.
