### ISSUE TITLE
Increased attester duties response times since Deneb

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6414]
### Describe the bug

From Holesky validator client metrics, the `getAttesterDuties` response time has gotten a lot more spiky since Deneb

![image](https://github.com/ChainSafe/lodestar/assets/38436224/0573bede-c045-49e2-84dc-72d11d785528)

There might also be a slight increase in signature times (needs further observations)

![image](https://github.com/ChainSafe/lodestar/assets/38436224/b683a7be-8e29-4b35-87d2-f3d29906889f)

### Expected behavior

Same performance / response times as in Capella

### Steps to reproduce

Run Lodestar vc <> bn on Holesky

### Additional context

More details / metrics can be found [on discord](https://discord.com/channels/593655374469660673/743858262864167062/1205215015339298907)

### Operating system

Linux

### Lodestar version or commit hash

v1.15.0

**Comment by eth2353** [comment]
I went through all the Lodestar dashboards to see if I could find any hints at what this could be caused by.

Here are the ones that stood out, hope it helps!

`increase(lodestar_stfn_state_cloned_count_count[1h])`

<img width="1479" alt="image" src="https://github.com/ChainSafe/lodestar/assets/70237279/a0edfbf7-022d-4c07-a1b3-da8169ae54da">

--> the states seems to be cloned 2x more often post-Deneb.

<img width="374" alt="image" src="https://github.com/ChainSafe/lodestar/assets/70237279/04e3f3e9-57a9-46d1-a4c4-75e9813404c7">

<img width="748" alt="image" src="https://github.com/ChainSafe/lodestar/assets/70237279/c8628134-8246-4e26-a7c3-81511bc2888d">

<img width="745" alt="image" src="https://github.com/ChainSafe/lodestar/assets/70237279/5dac2ce1-a830-4120-bc41-7d9fe414b5ad">

<img width="747" alt="image" src="https://github.com/ChainSafe/lodestar/assets/70237279/aeff8572-3f39-434f-a258-4f9760ba7583">

**Comment by twoeths** [comment]
looks like this time has been stable over time, this is in the last 30 days

<img width="1313" alt="Screenshot 2024-03-25 at 15 47 52" src="https://github.com/ChainSafe/lodestar/assets/10568965/cf888993-4766-4025-9da7-50798e8ba0d7">

on mainnet node it's quite good

<img width="1312" alt="Screenshot 2024-03-25 at 15 50 27" src="https://github.com/ChainSafe/lodestar/assets/10568965/1fb5b087-fc51-4e1b-9438-fdb5e16ad4c4">

**Comment by eth2353** [comment]
Performance looking good on our end nowadays too, running 1.17.0 though (issue was reported by us on 1.15.0). Feel free to close this Tuyen / team, seems to no longer be an issue! 🙂

**Comment by nflaig** [comment]
Looks good on my mainnet node as well, holesky also not too bad, closing this for now. Thanks @eth2353 for the metrics :pray:
