### ISSUE TITLE
Voluntary-exit exceeding a certain number of validator's keys results in HTTP header size error 

### ISSUE THREAD

**Issue by SpeakinTelnet** [ChainSafe/lodestar#6537]
### Describe the bug

When doing a volontary-exit using --importKeystores with what I assume is more than 128 validators the command fails with the following error:

```
 ✖ Error: Can not fetch state validators from beacon node - Request Header Fields Too Large: Exceeded maximum allowed HTTP header size
    at Function.assert (file:///opt/lodestar/packages/api/src/utils/client/httpClient.ts:44:13)
    at resolveValidatorIndexes (file:///opt/lodestar/packages/cli/src/cmds/validator/voluntaryExit.ts:213:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.handler (file:///opt/lodestar/packages/cli/src/cmds/validator/voluntaryExit.ts:100:30)
```

### Expected behavior

The validators should properly exit

### Steps to reproduce

Here's the full command I issued

`/usr/local/bin/node --trace-deprecation --max-old-space-size=4096   /opt/lodestar/packages/cli/bin/lodestar.js validator voluntary-exit   --network=gnosis   --dataDir=/var/opt/lodestar/chain-data   --importKeystores=/var/opt/lodestar/validator/keys   --importKeystoresPassword=/var/opt/lodestar/validator/password.txt`

### Additional context

I can exit by splitting the keys folder

### Operating system

Linux

### Lodestar version or commit hash

v1.17.0/stable/def26ac

**Comment by nflaig** [comment]
This is somewhat expected to happen if you run the command with too many keys because we call [getStateValidators](https://ethereum.github.io/beacon-APIs/#/Beacon/getStateValidators) which sends the pubkeys as part of the request query.

To resolve the issue on your end you have to set a extra flag on your beacon node to increase the max allowed header / url size via `--rest.headerLimit 65536` (defaut: 16384).

The long term solution for this is to switch to [postStateValidators](https://ethereum.github.io/beacon-APIs/#/Beacon/postStateValidators) which sends the pubkeys as part of the request body,

**Comment by SpeakinTelnet** [comment]
@nflaig Thank you for the clarification, the `--rest.headerLimit` did the trick!
