### ISSUE TITLE
Warning log when builder does not return a payload

### ISSUE THREAD

**Issue by mcdee** [ChainSafe/lodestar#6574]
### Describe the bug

As per https://ethereum.github.io/builder-specs/#/Builder/getHeader it is possible for the call to `/eth/v1/builder/header/{slot}/{parent_hash}/{pubkey}` to return a 204 status and no body.  In this situation lodestar generates a warning in the logs due to the lack of body in the response.

### Expected behavior

The behavior should be considered normal and not warrant a warning in the logs.

### Additional context

Log when this occurs:

```
Mar-21 10:41:00.437[api]              warn: Builder failed to produce the block fork=deneb, builderSelection=maxprofit, slot=4607005, isBuilderEnabled=true, isEngineEnabled=true, strictFeeRecipientCheck=undefined, builderBoostFactor=100, durationMs=5 - Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5329:19)
    at successSteps (node:internal/deps/undici/undici:5300:27)
    at specConsumeBody (node:internal/deps/undici/undici:5306:9)
    at _Response.json (node:internal/deps/undici/undici:5196:18)
    at file:///home/lodestar/lodestar/packages/api/src/utils/client/httpClient.ts:171:66
    at HttpClient.requestWithBody (file:///home/lodestar/lodestar/packages/api/src/utils/client/httpClient.ts:342:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.request [as getHeader] (file:///home/lodestar/lodestar/packages/api/src/utils/client/client.ts:86:23)
    at ExecutionBuilderHttp.getHeader (file:///home/lodestar/lodestar/packages/beacon-node/src/execution/builder/http.ts:111:17)
```

### Operating system

Linux

### Lodestar version or commit hash

v1.16.0

**Comment by nflaig** [comment]
> The behavior should be considered normal and not warrant a warning in the logs.

The error is pretty bad as noted in https://github.com/ChainSafe/lodestar/issues/5826, we shouldn't try to parse it as json if we receive a 204 http status code. This seems to be blocked by the ssz refactor I am currently working on as right now we always try to parse the response body if it is defined for the API which is the case here as we need it for the 200 response.

What we should do instead is inspect the status code, and if it is 204 we have to set the block value to `null` and make sure our fallback handling to local block still works and adapt logging accordingly, i.e. an acutal error should be `warn` while the 204 case we might rather want to log as `info`.

**Comment by nflaig** [comment]
> The behavior should be considered normal and not warrant a warning in the logs.

Was thinking a bit more about this, we definitely need to improve the warning we are logging in this case but from the point of view of the beacon node this should be considered an error as it was asking for an execution payload header but didn't receive it, and if the local block production fails as well this means a missed proposal.

The only reason this is considered normal behavior is because of `min-bid` is implemented on mev-boost side but it should probably have been implemented on the beacon node in the first place (https://github.com/ChainSafe/lodestar/issues/6602) and also be passed as a query param by the validator client when producing the block.

**Comment by mcdee** [comment]
> it was asking for an execution payload header but didn't receive it,

This is a totally valid situation, and why there is a specific return code in the spec to handle the situation.  There is no guarantee that a relay has a payload for every slot.  This is especially true of testnets, but stands for mainnet as well.

**Comment by nflaig** [comment]
> There is no guarantee that a relay has a payload for every slot. This is especially true of testnets, but stands for mainnet as well.

There is no API that guarantees that it can't fail, especially since are talking about HTTP requests over the network, also see discussion around get aggregate attestation https://github.com/ethereum/beacon-APIs/issues/109 but considering  the request a success if the server fails to provide the requested data makes no sense to me and is just bad API design in my opinion.

**Comment by mcdee** [comment]
I'd suggest that there's a difference between hitting an endpoint that exists but has no useful data to give you, and hitting an endpoint that doesn't exist.  The API as stands allows differentiation between these two situations.

As to if a 204 should result in a warning in the lodestar logs, that's your call.

**Comment by nflaig** [comment]
> I'd suggest that there's a difference between hitting an endpoint that exists but has no useful data to give you, and hitting an endpoint that doesn't exist.

I get your point but I just don't see how that's useful in reality. We have a well defined spec and clients should know the APIs they are calling, a 404 due to a missing route is not something that's likely to happen. And rather a better solution would be for the server to return 501 if it does not yet implement a API required by the spec.

> The API as stands allows differentiation between these two situations.

Do you have an example where this makes a practical difference? I really look at this from a pure implementation point of view as anyhow the HTTP status codes are lacking in many ways.

**Comment by nflaig** [comment]
> Do you have an example where this makes a practical difference?

So one thing I can think of is maybe if you wanna fallback to an earlier version of API, e.g. if you get 404 when calling `produceBlockV3` you would retry `produceBlockv2` but in a lot of cases relying on 404 for that is unreliable because it's not the equivalent of 501 (not implemented), e.g. what if path params are incorrect, this might result in 404 as well

**Comment by mcdee** [comment]
Some relays have the ability to turn off their ability to serve payloads if they have potential issues, but remain operational so would be returning 204.  Other times we have seen relays switch off entirely and be replaced with a "we are no longer here" page, and requests return 404.  We wouldn't want to receive errors for the former, and we would want to receive errors for the latter.

**Comment by nflaig** [comment]
> Some relays have the ability to turn off their ability to serve payloads if they have potential issues, but remain operational so would be returning 204.

If they can't serve payloads they should not be returning success responses, HTTP has a well defined status code for such cases which is to return a [503 Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503). It's much simpler to just have a well defined success response and error response(s), having to inspect status codes of success responses to determine if the requested data was delivered is just a mess.

![image](https://github.com/ChainSafe/lodestar/assets/38436224/42a8632a-bdbd-4e30-8306-43123f0bc5f5)


> Other times we have seen relays switch off entirely and be replaced with a "we are no longer here" page, and requests return 404. We wouldn't want to receive errors for the former, and we would want to receive errors for the latter.

And what if the relayer decides to just completely shut down the server you would get a network error, but the network error might be due to other reasons as well. This sounds like a big headache to handle all those cases programmatically, and likely in the end you rely on the error message to figure out what's going on.

I am not sure if anyone implements this? I am not aware of mev-boost even having this

**Comment by matthewkeil** [comment]
> The behavior should be considered normal and not warrant a warning in the logs.

FWIW I agree with the initial premise of this and lean towards an "info" log level. 

> If they can't serve payloads they should not be returning success responses

Not sure I agree with that... If there is a valid request and the valid response from the service is `null` then it should come with a "valid" 2XX status code as the service is available.  This feels like the same situation as there is "no bid" available but just represents a longer timeframe.  503 does not feel correct because often times clients have retry built in based on 5XX and in that situation where the service is not "interested in serving" at the moment there would be multiple calls.
