### ISSUE TITLE
Validator process checks beacon sync state too infrequently

### ISSUE THREAD

**Issue by barnabasbusa** [ChainSafe/lodestar#6962]
### Describe the bug

Currently the validator process checks whether a beacon node is synced or not once every epoch. This feels a bit too infrequent. 

### Expected behavior

It would be good for the validator to check sync status every slot instead. 

### Steps to reproduce

Get your beacon node to get unsynced (200-300 slots) - start it back up, and keep an eye on the validator logs

### Operating system

Linux

### Lodestar version or commit hash

v1.20.1 - docker

**Comment by nflaig** [comment]
We are not checking if beacon node is synced by calling `/eth/v1/node/syncing` explicitly but it's determined based on 503 status code when calling other apis. But this is indeed an issue that we only poll validator duties once an epoch even if request fails due to node syncing or other reasons. We should ideally increase polling frequency to once per slot if we can't obtain duties.
