### ISSUE TITLE
Electra: Implement EIP7742: uncouple blob limits per block across CL and EL

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#7176]
### Problem description

As determined in [ACDC #144](https://github.com/ethereum/pm/issues/1178), EIP-7742 is moving into CFI with teams signalling to implement for Pectra devnet-5.

### Solution description

Reference: https://github.com/ethereum/consensus-specs/pull/3800
EIP: https://eips.ethereum.org/EIPS/eip-7742
Engine-API update: https://github.com/ethereum/execution-apis/pull/574

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ensi321** [comment]
The consensus specs session held during devcon mentioned we want to move forward by experimenting different combination of `target_blobs_per_block` and `max_blobs_per_block`. 

We can implement a version of Lodestar that allows these values to be configurable, instead of being dictated by `MAX_BLOBS_PER_BLOCK` as stated [here](https://github.com/ethereum/consensus-specs/blob/e3eb09b71604374a253025f80598d27f5bd88508/specs/electra/validator.md?plain=1#L179).

I will work on this @g11tech

**Comment by ensi321** [comment]
We have decided to shelve this EIP in Pectra as per [ACD#147](https://github.com/ethereum/pm/issues/1211). Might revisit in Fulu
