### ISSUE TITLE
Fix duplicate status request

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#819]
Because we don't distinguish inbound or outbound peer in "peer:connect" we send status request if we are dealer or receiver. According to spec we should only send status request if we are dialer. We should probably additionally emit "peer:inbound:connected" and "peer:outbound:connected" and only send status request if we encouter later event

**Comment by twoeths** [comment]
I can't find a place in `libp2p` to differentiate dialer and listener. My approach is to override libp2p `dialProtocol` and maintain a `dials` set in our libp2p in order to differentiate it.
+ In `dialProtocol`, add peer-info/peer-id to `dials` set
+ On "peer:connect", if the peerInfo is in `dials` set then emit "peer:outbound:connected", otherwise emit "peer:inbound:connected"
+ On "peer:disconnect", remove the peerInfo/peer id from `dials` list

What do you think?

**Comment by mpetrunic** [comment]
This is already fixed!
