### ISSUE TITLE
Ensure beacon node cleanly exits

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#880]
**Describe the bug**
When starting the chain without a genesis state, not all modules are started, since `BeaconChain` blocks on `start` until a genesis state has been created.
If the node is stopped during this time, the node is not stopped properly, because other modules' `stop` method assumes that all modules have been started.

**Expected behavior**
Beacon node should exit cleanly, even if all modules have not started.

**Steps to Reproduce**
start lodecli, using eth1 to trigger genesis, eg: using https://hackmd.io/2wNvrO77RQ6BWc2ZA7M0Cg
Once the node has started, hit Ctrl+C
Instead of exiting, an unhandled promise rejection is thrown

**Comment by lastmjs** [comment]
I'd be happy to dig into this, what do you think?

**Comment by wemeetagain** [comment]
Oh yea, go for it

**Comment by lastmjs** [comment]
Hey, this might be a larger discussion better had elsewhere, but I noticed that strictNullChecks is set to false in the main tsconfig. What's the reasoning there? This issue would have been caught already if strictNullChecks were true. It looks probable that there are many hidden issues like this that will be uncovered with strictNullChecks set to true.

Hold on, I may have spoken too soon. My editor might be lagging

**Comment by lastmjs** [comment]
There are a couple ways to go about this from what I can tell. There seem to be a lot of places where we aren't checking if variables hold values that are defined, leading to this situation and probably many others that are currently hidden. I could just put in some definition checks and call it good, but I'm running into a bit of a problem with the `libp2p-gossipsub` library.

If you try to call the `stop` method of a `GossipSub` instance, it will actually throw an error because `this._heartbeatTimer` is not defined. So it looks like `GossipSub` believes it is invalid to call stop if start hasn't been called. I'm not sure how to get around this, is there some public state in a `GossipSub` instance that I can use to determine if stop needs to be called?

This problem leads me to another potential solution (not sure if it would be a full solution). Instead of just doing these definition checks, what if each of these modules kept a `started` state within them. When a module/service starts, we can set `started` to true. If you call stop and `started` hasn't been called, then stop will do nothing. This could help.

I could also just catch the heartbeat error and ignore it

**Comment by wemeetagain** [comment]
re: `strictNullChecks`, not sure there's a good reasoning for it being false. Definitely think we should rip the bandaid off at some point.

I think tracking the `started` state in each module would help, we already do this in a few modules (eth1 and sync).

**Comment by lastmjs** [comment]
> re: strictNullChecks, not sure there's a good reasoning for it being false. Definitely think we should rip the bandaid off at some point.

When do you think we should rip the bandaid off? Should I open an issue for this? Will probably take some significant tedious effort across the entire codebase. Also it might be good to have a null/undefined strategy if there isn't one already. Such as always using undefined, always using null, or deciding when to use each. There's also the option of never using undefined or null if possible, such as creating types that are more descriptive, i.e. `NOT_SET`.

Example:

```typescript
  public clock: IBeaconClock | "NOT_SET";
```
You could also say "NOT_INITIALIZED", "NOT_STARTED", or something. I have found this to be a pretty nice way to do things, not without its own problems of course. `null` and `undefined` are just such problematic and broad types.

**Comment by wemeetagain** [comment]
Yeah, please do. :) I think we should do this as soon as feasible, as it won't be getting any easier the longer we wait. Agreed, it'll be a tedious kind of thing.
